### ISSUE TITLE
Instanciating Scala case classes

### ISSUE THREAD

**Issue by jonathan-laurent** [jpype-project/jpype#1005]
First of all, thanks for this great project!
I am trying to use jpype to use a Scala library from Python and one obstacle I've encountered is instantiating case classes.

Here is a [snippet](https://gist.github.com/andypetrella/6f3df40034aad48591d7f28d1c7697ff) to do it with Py4j:

```python
# This function takes the fully classified object name, say: <package>.<name>.
# Returns the static object instance on the heap

def ref_scala_object(object_name):
  clazz = jvm.java.lang.Class.forName(object_name+"$")
  ff = clazz.getDeclaredField("MODULE$")
  o = ff.get(None)
  return o
```

I was wondering if there was a similar way to do it using jypye. Because `MODULE$` is not a valid identifier in Python, I do not see how access this field using jpype.

**Comment by Thrameos** [comment]
It isn't really clear to me what this object type is and how it is supposed to be accessed.  The code that you executed in Py4J should run in JPype.   If you would like to exposed it as  something else, you would need to alter the code in org.jpype regarding the TypeManager.   It provides the facilities to decide how each item is to be presented in Python can creates the wrappers.   These are then presented to the Python wrapper maker in jpype/_jclass which hooks them up to the Python type.   

Of course just because the name is not directly usable in Python it may still exist.  You would just need to use getattr.

Perhaps something like this will work?
```
cls = java.lang.Class.forName(object_name+"$")
return getattr(cls, "MODULE$")
```

**Comment by jonathan-laurent** [comment]
For reference, the proposed solution above worked if one replaces `getattr` by `getDeclaredField`:

```python
cls = java.lang.Class.forName(cls.__name__ + "$")
return cls.getDeclaredField("MODULE$").get(None)
```
