### ISSUE TITLE
Using Temporary Directory to store classpath Jars causes File in use error in Windows on exit

### ISSUE THREAD

**Issue by Christopher-Chianelli** [jpype-project/jpype#1006]
Using a Temporary Directory to store classpath Jars causes File in use error in Windows on exit.

Example:
```python
import jpype
import tempfile
import os

my_jars = tempfile.TemporaryDirectory()


def extract_jars() -> list[str]:
    classpath_list = pkg_resources.read_text('mypackage', 'classpath.txt').splitlines()
    classpath = []
    for jar in classpath_list:
        new_classpath_item = os.path.join(my_jars.name, jar)
        jar_file = pkg_resources.read_binary(jars, jar)
        with open(new_classpath_item, 'wb') as temp_file:
            temp_file.write(jar_file)
        classpath.append(new_classpath_item)
    return classpath

jpype.startJVM(*args, classpath=extract_jars())

# ... additional code that uses java + python
```

causes the following error on exit:
```
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpy3fynomc\\dependency.jar

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\tempfile.py", line 801, in onerror
    _os.unlink(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpy3fynomc\\dependency.jar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\weakref.py", line 656, in _exitfunc
    f()
  File "C:\Program Files\Python39\lib\weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Program Files\Python39\lib\tempfile.py", line 816, in _cleanup
    cls._rmtree(name)
  File "C:\Program Files\Python39\lib\tempfile.py", line 812, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Program Files\Python39\lib\tempfile.py", line 804, in onerror
    cls._rmtree(path)
  File "C:\Program Files\Python39\lib\tempfile.py", line 812, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Program Files\Python39\lib\shutil.py", line 599, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Program Files\Python39\lib\shutil.py", line 596, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmpy3fynomc\\dependency.jar'

Process finished with exit code 1
```

Expected behaviour: Process exits without any errors

Use case: Storing dependency jars in package for Java wrapper python packages.

Workaround: Calling `System.exit(0)` with an `atexit` hook prevents this error. Calling `jpype.shutdownJVM()` with an `atexit` hook does not prevent this error. Might be related to https://github.com/jpype-project/jpype/issues/936

**Comment by Thrameos** [comment]
I believe this is expected behavior given the design of the JVM.   JPype loads the JVM and the JVM loads jar files as shared files which are held by the classloader forever after the load point.   Because the design of JVM it can't unload files once loaded.   And by design you can't unload the JVM as it does not have clean up routines to remove hooks.   

The System.exit(0) just terminates the process which skips the cleanup routines so that really isn't addressing it.

So my question here is about ordering.   Did the file deletion happen before or after the JVM shutdown was complete?   If it was before then the files are still open which causes the error.  If they were after then we need another solution.   

Here is my suggestion.   The dynamic classloader in JPype can load a jar after the JVM is started.   If you can find a solution to perform this task in pure Java, you can port it to JPype by creating a temporary directory using Java which uses the Dynamic loader which uses instances of URLLoaders.   Those loader can potentially be destroyed releasing the resources in the Java atexit logic.  See ``org.jpype.JPypeContext.getInstance().addShutdownHook()`` for how to add a method to the shutdown sequence.

**Comment by Christopher-Chianelli** [comment]
If `jpype.shutdownJVM()` waits for JVM shutdown to be completed when called, the files are deleted after the JVM shutdown is complete.

On the other hand, if `jpype.shutdownJVM()`  is async or does a partial shutdown, then it probably called before the JVM shutdown is complete.

I checked manually with print statements, so I know `jpype.shutdownJVM()` is called before the file is deleted with my custom at exit hook). (Note: I don't delete the temporary directory; Python does it at exit).

I can look into porting the jar extraction code into the Java side (although it'll be a bit of a pain since I need to extract the jars from the python package, which itself might be zipped/compressed).

**Comment by Christopher-Chianelli** [comment]
I use the files directly via importlib.metadata:

```python
jars = [str(p.locate()) for p in importlib.metadata.files('optapy') if p.name.endswith('.jar')]
```

Thus, avoiding the use of a temporary directory entirely. The issue still exists in Windows; by guess is the Java process is still running after `jpype.shutdownJVM()` is called (but in a different thread).
