### ISSUE TITLE
convertStrings=True cut Java returned Strings with NULL bytes short

### ISSUE THREAD

**Issue by Christopher-Chianelli** [jpype-project/jpype#1091]
#  Summary

When `jpype.startJVM(convertStrings=True)` is used, returned Strings with NULL bytes are cut short.
This behavior is not observed when `jpype.startJVM(convertStrings=False)` is used.

## Example Reproducer

Code is available at: https://github.com/Christopher-Chianelli/issue-reproducer/tree/jpype-null-bytes-in-string

Java class:
```java
package org.acme;

public class MyClass {
    public static int getLength(String argument) {
        return argument.length();
    }

    public static String getArgument(String argument) {
        return argument;
    }
}
```

Python code
```python
import jpype
import jpype.imports

jpype.startJVM(classpath=[...], convertStrings=True)

from org.acme import MyClass

# Passing a string with NULL bytes to Java works
assert MyClass.getLength('\u0000') == 1

# Reading a returned string with NULL bytes from Java fails
out = MyClass.getArgument('String\u0000with\u0000NULL\u0000Bytes')
print(out)

assert out == 'String\u0000with\u0000NULL\u0000Bytes'
```

### Expected Behavior

`out == 'String\u0000with\u0000NULL\u0000Bytes'`

### Actual Behavior

`out == 'String'`

**Comment by Christopher-Chianelli** [comment]
I think this is caused by this line:

https://github.com/jpype-project/jpype/blob/82a7658277b36c628ea305ea705cd012d81471dd/native/common/jp_stringtype.cpp#L50

which cause a string with null bytes to be terminated early. `PyUnicode_FromStringAndSize` (https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_FromStringAndSize ) might fix the issue.

**Comment by Thrameos** [comment]
It does appear that nulls will present a problem.   Looking through the code the issue was introduced because the original in 0.6.2 just took the Java encoded string and passed it directly to Python with the specified length.  This was buggy because Java and Python use different encodings so when we had different encodings the Python strings were busted and sometimes led crashes.    It should be possible to switch to PyUnicode_FromStringAndSize.
