### ISSUE TITLE
Whether python can inherit from java classes

### ISSUE THREAD

**Issue by hhhhh322** [jpype-project/jpype#1172]
I looked at the documentation, but since I'm not a native English speaker, the documentation wasn't clear about whether the python class could inherit from the java class, so I tried to use JImplementationFor inheritance, but it was very noticeable that I got an error like this: TypeError: 
No matching overloads found for constructor com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.

The documentation seems to indicate that JPYPE doesn't support inheritance from Java classes, so I'm going to ask for that.

**Comment by Thrameos** [comment]
JPype cannot extend a class.   JPype can implement an interface.   The method to implement an interface requires ***@***.***” rather than placing the class in the Python inheritance.   To extend a class you will need to add a stub that redirects the desired methods to an interface.  This is a limitation of Java in that you can’t access private methods and members, nor generate the required stubs as Java is a compiled language, so runtime extension of a class requires on the fly compiling which isn’t possible currently.
