### ISSUE TITLE
Python 3.13 problems

### ISSUE THREAD

**Issue by astrelsky** [jpype-project/jpype#1204]
This is now problematic because `PyType_IS_GC` implies it is on the heap and the pointer gets cast to `PyHeapTypeObject`. It will eventually read memory on the stack and interpret it to be some huge size and it will result in a `MemoryError`.

https://github.com/jpype-project/jpype/blob/653ccffd1df46e4d472217d77f592326ae3d3690/native/python/pyjp_value.cpp#L51-L59

I have tried replacing it with [PyUnstable_Object_GC_NewWithExtraData](https://docs.python.org/3.13/c-api/gcsupport.html#c.PyUnstable_Object_GC_NewWithExtraData) but it can't handle `nitems > 0`. So I tried the following:
```c++
#if PY_VERSION_HEX>=0x030d0000
		PyHeapTypeObject heapType = *(PyHeapTypeObject *)type;
		PyTypeObject type2;
		type2.tp_basicsize = size;
		type2.tp_itemsize = 0;
		type2.tp_name = nullptr;
		type2.tp_flags = type->tp_flags;
		type2.tp_traverse = type->tp_traverse;
		heapType.ht_type = type2;
		obj = PyObject_GC_New(PyObject, &heapType.ht_type);
#else
```

That works fine until here
https://github.com/jpype-project/jpype/blob/653ccffd1df46e4d472217d77f592326ae3d3690/native/python/pyjp_value.cpp#L215

Unfortunately it then tries to access `(PyDictValues *)((char *)obj + sizeof(PyObject))` when it is not valid. The value at `PyDictValues->valid` is not zero so its checks pass and it moves forward until it faults. I suspect the java slot is being put isomewhere python is using and causing memory corruption but I haven't been able to prove it or find out what is really wrong.

**Comment by Thrameos** [comment]
They have made it very difficult to allocate memory with differing layouts.  I tried to propse a fix, but it required putting in a PEP.  Unfortunately I was almost immediately hit with an emergency at work and have been unable to find any time since.

The solution to this problem would be to create an actual heap type first then use it to allocate the desired memory rather than this static type hack.  Or they need to give back access to making gc allocations.  Given there is a slot for allocators, removing the gc call private basic deprecates the slot function.

I wish I had the time to persue the PEP but I have another 3 months of work before I can cycle back to major work here.

**Comment by astrelsky** [comment]
What I'm having trouble understanding is why this is even necessary at all? Shouldn't you be doing something like this?

Mostly copypasta from https://docs.python.org/3.13/extending/newtypes_tutorial.html#the-basics
```c++
struct JPValueObject {
	PyObject_HEAD;
	JPValue slot;
};

static PyTypeObject JPValueType = {
	.ob_base = PyVarObject_HEAD_INIT(NULL, 0)
	.tp_name = "custom.Custom",
	.tp_basicsize = sizeof(JPValueObject),
	.tp_itemsize = 0,
	.tp_flags = Py_TPFLAGS_DEFAULT,
	.tp_new = PyType_GenericNew,
};

JPValue* PyJPValue_getJavaSlot(PyObject* self)
{
	if (PyObject_IsInstance(self, (PyObject *)&JPValueType)) {
		return &((JPValueObject *) self)->slot;
	}
	return nullptr;
}
```


The only one I foresee causing trouble would be `PyJPClass` since it's a metaclass and metaclasses that override `tp_new` are not allowed.

I'm sure there was a reason, if only at one point in time, for doing it the way it is, I'm just not seeing why.

**Comment by Thrameos** [comment]
Unfortunately you missed something vital.  The Java slot can't appear in the structure at all.  We are using this as a mixin because we must be compatible with all possible Python concrete types. If you try to put it in the structure then it will conflict with int, float, exception etc which we must derive from as all base types are concrete.  We thus used the alloc slot to adjust shift the Python structure down 8 bytes and added the needed data in front of the Python structure where we could always guarantee access at order 1.  The issue is that Python developers decided to start placing their info in front to the Python object with no api to handle conflicts.   This basically breaks the whole concept of the alloc slot as you have no way to alloc object memory with variable size.  

I wrote a PR to give an API but have no way to pursue it.

**Comment by astrelsky** [comment]
So it seems to be a combination of problems. First is the one already discussed and the second I think is changes to how a type is created which makes `PyJPClass_FromSpecWithBases` no longer work properly.

I had hoped to be able to figure out the problem myself and have my employer submit the fix. Unfortunately it would probably require significant refactoring that would take me months, due to the lack of familiarity with the jpype internals, and I'm not able to justify it. It seems the best way would be to tell you what I know and let you handle it.

The only thing I could think of that might not require a major rework would be to stick the `JPValue` in a python object and assign it as a member def. This pretty much defeats the whole purpose of having the type implemented in c++ though.


Also, c++ not supporting c99 designated initializers is extremely annoying.

**Comment by Thrameos** [comment]
Thanks, I will take a look.

--Karl

**Comment by astrelsky** [comment]
I have some ideas that should create a path forward with less issues, it will just require a non-trivial refactor. The main caveat would be that each `JClass` instance would require two python object allocations. With the exception of primitive types and exceptions, they would be a generic object where you could place the jobject instance at the end. I think having each type have it's own allocator where necessary instead of all of them using the same allocator will reduce the amount of problems going forward. I expect to run into a handful of roadblocks but it is a problem I am interested in and have no problems spending all of my personal time on it. (Note: communication is difficult for me, if this didn't make much sense, don't worry about it).

The biggest challenge I'll likely face is getting it working and finishing before I lose interest 😅

**Comment by Thrameos** [comment]
There were serious issues with the two object approach which is why it was abandoned in Jpype 0.7.  The biggest being Isa relations.  Primitives, exceptions and the like can't be duck typed to meet their contracts.  The must be inherited directly from the Python objects they seek to emulate.  They also have there own incomparable memory layouts.  And for float and long you can't add anything to the base.  You can make a special exception type for it's objects.

This brings about the second issue which is the look up time.  If you have many layouts then figuring out if it is a class derivative takes time.  With the double object we used this was a substantial number of calls.  And to test a method overload yous have to check for it for each combination of overloads.  If we break that jpype gets rather slow.  We could bypass this requirement by adding a slot offset to the type object meta class.  

All the other language binders have the same problem and thus a get user data method was to be added to basic Python object system, but the implementation missed as it was still incomplete with int, float, and exception (they didn't test can this inherit from every python type).  The solution is to fix their type system by making a facility for any type to access user data in O(1).  It isn't hard as I already submitted a patch.  

Trying to fix it at jpype end as they have constantly changing their type system is a losing battle.  I would recommend taking the time for the for all solution which is trivial (negative baseline implies the data will be added to the preheader) rather than reworking jpype where you will get a dozen edge cases.

**Comment by astrelsky** [comment]
> There were serious issues with the two object approach which is why it was abandoned in Jpype 0.7.  The biggest being Isa relations.  Primitives, exceptions and the like can't be duck typed to meet their contracts.  The must be inherited directly from the Python objects they seek to emulate.  They also have there own incomparable memory layouts.  And for float and long you can't add anything to the base.  You can make a special exception type for it's objects.
> 
> This brings about the second issue which is the look up time.  If you have many layouts then figuring out if it is a class derivative takes time.  With the double object we used this was a substantial number of calls.  And to test a method overload yous have to check for it for each combination of overloads.  If we break that jpype gets rather slow.  We could bypass this requirement by adding a slot offset to the type object meta class.  
> 
> All the other language binders have the same problem and thus a get user data method was to be added to basic Python object system, but the implementation missed as it was still incomplete with int, float, and exception (they didn't test can this inherit from every python type).  The solution is to fix their type system by making a facility for any type to access user data in O(1).  It isn't hard as I already submitted a patch.  
> 
> Trying to fix it at jpype end as they have constantly changing their type system is a losing battle.  I would recommend taking the time for the for all solution which is trivial (negative baseline implies the data will be added to the preheader) rather than reworking jpype where you will get a dozen edge cases.
> 

I am tracking the conversation in the pull request. Hopefully things go in the right direction. For now I will stand by and be quiet.

**Comment by Thrameos** [comment]
Sounds good.  There are only three changes in Python that are needed to eliminate all of the black magic that we are doing.  

1) The multiple inheritance patch which adds our data.
2) A method to inject stack frames from Java exceptions.
3) A way to lazy load strings so that Java and Python strings can be unified.

Many language binding (ie C#) need these same pieces.   Each isn't that complex, but it will take time and effort to press them forward.
