### ISSUE TITLE
Pre-built wheels for Linux on ARM?

### ISSUE THREAD

**Issue by sindre-nistad** [jpype-project/jpype#1215]
Would it be possible to distribute pre-built wheels for `linux-aarch64` on PyPi?

My use-case is using `JPype1` (through `JayDeBeApi`) on a docker container running on Apple Silicon.
Currently, we compile `JPype1` from source while building the container, which takes a little while in addition to installing the necessary compiler and libraries.

On a slight side-note; thank you very much for this library 😊 
It has / is very useful when I have to interact with some vendor-provided Java programs / libraries.

**Comment by Thrameos** [comment]
We use the `.azure` scripts to build all the architectures that we currently distribute.  Assuming you can find a recipe to create such a build using the Microsoft Azure cloud, I can add it to the distribution.   I would guess that adding another OSX job as found in ``release.yml`` (line 144) with a different image/python.architecture file should produce the additional images.   We also had a pattern for producing docker based distributions in the past though that was with a previous cloud.   I am not sure if we have been successful on azure.  

If you want to work on that I believe that you just need to clone the repo, open a azure cloud account, then trigger the release pipeline on your fork.   Unfortunately, due to other time commitments I can't work on this myself, but would be happy to accept a contribution if others can work out the pattern.   It has been an ongoing problem in which either the Python arch or the Java arch fail to match.   I know it is possible to build and run assuming both are matching and thus we can distribute it.  


Here is what limited research that I found relevant to the topic:

I have previous found lists of the available vmImages.  We are using osx-11 which as far as I am aware is a x64 image.

https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml


It appears that there should be a pool of machines for arm64 released in 2023, though I am not sure how to specify the target.

https://github.com/Azure/azure-dev/issues/1314


There are some posts indicating that as of a year ago Python compilations against arm64 did not work on Azure.  But I haven't the time to follow through to see if that condition has changed.    This would need to be resolved before a successful build is possible.

https://stackoverflow.com/questions/75988713/microsoft-azure-webjobs-script-architecture-arm64-is-not-supported-for-language

**Comment by sindre-nistad** [comment]
Thanks,
I'll look into it. I have experience working with Azure

**Comment by meijiesky** [comment]
Only 1.2.1 is prebuilt for pip install and the later releases are not. Please refer to https://github.com/jpype-project/jpype/issues/1227 and I don't understand why my issue is closed.

**Comment by marscher** [comment]
https://github.com/jpype-project/jpype/pull/910 something seems to be broken.

**Comment by sindre-nistad** [comment]
> @sindre-nistad did you have the chance to take a look and point us toward a solution? Thanks

Unfortunately, I haven't :(

**Comment by marscher** [comment]
I think we have it almost solved in #1234

**Comment by marscher** [comment]
The aarch64 users should be happy now with version 1.5.1. Please check it out.
