### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by kutschkem** [jpype-project/jpype#140]
Some error messages don't give enough information for my taste. For example, the jp_method.cpp, the message "No matching overload found" should include information about the method name and the parameters that were searched.

**Comment by baztian** [comment]
"Some error messages"  is a bit vague. Would be great if you can provide a pull request.

**Comment by kutschkem** [comment]
:-P Fair enough. I meant explicitly that error message, since it is rather common and doesn't disclose what method it is trying to find with which parameters.

**Comment by marscher** [comment]
I think it should be easy to just display the prototype of the function called, but "stringifying" all candidates (just in case of no match) is overkill and is likely to hurt performance.

**Comment by Thrameos** [comment]
This is currently in the master branch with better text in the devel branch.  The question of performance depends on how often that an exception is issues.  The default case in python is that exceptions should be fairly light as it is supposed to be okay to try first and ask permission later.  However, this is a runtime  exception in which there is likely not going to be a good recovery, thus giving good feed back should not be an issue.  If we are concerned about performance, then we for this we should cache the alternative methods string on the first occurrence.

We will have a similar problem when we consider tracing information.  For the ease of users it is a good idea to have a fully integrated tracing output between Java, C++  and Python so that all the excecution path is clear.  But this means more overhead as we have to fake a traceback on the exception handling to create a object that knows the stack dump with the Java exception, the C++ stack and the existing python.  Python has pretty low overhead as it just keeps track of the internal execution stack.  But JPype does not have that option.  Thus we are going to need to decide which exception paths need to follow the Python philosophy and run with low overhead (say array out of bounds) and which we should pay the full price of clarity.
