### ISSUE TITLE
mixed line endings in repository

### ISSUE THREAD

**Issue by marscher** [jpype-project/jpype#205]
We have 157 files with crlf (\r\n) ending and 47 with lf (\n). This should be unified once and enforced by .gitattributes

**Comment by Thrameos** [comment]
This one is not hard to fix (mass dos2unix and add the .gitattributes), but it will break virtually all existing forks and incoming patches from those forks.  Git would natively like everything in the repo as being \n and then convert to the system specific on push and pull.  I would recommend just choosing a time when the incoming pull requests are all either accepted or rejected.

**Comment by Thrameos** [comment]
As we are approaching a release it may be a good time exercise this.   I would submit a patch but as it is a full source line patch I think that it your honor, @marscher. I have only a one large cleanup patch out which is I can easily do a port forward as I have an extracted patch.   

I think my next batch of time will likely be to resolve the issues with python nightly and PyPy.   Both seem to be issues with the module start up and hitting some undocumented behavior with the calls to tuple and sequence interfaces.  Those fixes will hit a lot of files because they change some of the C++ wrapper classes so I have been holding off until we decide if we are going to make this change.

**Comment by Thrameos** [comment]
This has been completed.
