### ISSUE TITLE
Integration between java.lang.Date and python datetime

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#242]
My coworker requests for plotting time based data an integration between java.lang.Date and datetime such that a java.lang.Date can be used in place of a datetime.  I have implemented this but it depends on the Boxed patch.

**Comment by claytondaley** [comment]
Is there an general limitation with Python `datetime` conversion to Java?  Or is this issue specific to `java.lang.Date`?  I ask because I'm running into an issue that would be consistent with issues converting python `datetime` classes to java.

**Comment by Thrameos** [comment]
I remember it being an issue getting Python date concepts to communicate with Java.  I though that we did end up with a linkage to Instant though that may be in devel branch.

--Karl

**Comment by claytondaley** [comment]
Thanks.  I didn't find `datetime` anywhere in the codebase (either `master` or `devel`) but I may not be looking in the right way/place.  After a *lot* of digging, I eventually landed on the following workaround in case it's useful to anyone (**note: this casts to java.sql types since I was working with a JDBC driver**):

```
def dt_to_java(obj):
    if obj is None:
        return None
    if isinstance(obj, datetime.datetime):
        seconds = (obj - datetime.datetime.min).total_seconds()
        return jpype.java.sql.Timestamp(int(round(seconds * 1000)))
    elif isinstance(obj, datetime.date):
        seconds = (obj - datetime.date.min).total_seconds()
        return jpype.java.sql.Date(int(round(seconds * 1000)))
    elif isinstance(obj, datetime.time):
        seconds = (datetime.datetime.combine(datetime.date.min, obj) - datetime.datetime.min).total_seconds()
        return jpype.java.sql.Time(int(round(seconds * 1000)))
    else:
        raise TypeError("Could not convert type:  {}".format(obj.__class__.__name__))

```

The method is (horribly) indirect because:
 - The only non-deprecated Java constructors (in [java.sql](https://courses.cs.washington.edu/courses/cse341/98au/java/jdk1.2beta4/docs/api/java/sql/Timestamp.html#Timestamp(int,%20int,%20int,%20int,%20int,%20int,%20int))) accept a single millisecond time value (of type long).
 - Python's timedeltas are an especially convenient way of generating seconds.  Obviously, I'm ignoring the microseconds, but they could be added in.
 - Unfortunately, `total_seconds` returns a float which `JLong` will not cast so I had to cast to an `int` (Py3 doesn't make the `long` distinction).
