### ISSUE TITLE
java.security.Certificate.class_.<tab> in IPython shell causes a crash

### ISSUE THREAD

**Issue by KOLANICH** [jpype-project/jpype#308]
`dir(java.security.Certificate.class_)` works fine. Needs investigation, but I don't have time for it for now.

**Comment by Thrameos** [comment]
It does not replicate for me with Python 3.6.3, IPython 6.2.1 under Spyder 3.2.5 on a windows i686 architecture.

```
> import jpype
> import jpype.imports
> jpype.startJVM(jpype.getDefaultJVMPath())
>import java.security.Certificate
>java.security.Certificate
Out[5]: jpype._jclass.java.security.Certificate

>java.security.Certificate.class_
Out[6]: <jpype._jclass.java.lang.Class at 0x891eba8>

>java.security.Certificate.class_.<tab>
(Big list of methods)
```

I have seen this happen before but I have never successfully replicated it myself.  I have some suspected causes, but being unable to replicate it I can't isolate the problem.  My coworker hit it by running a large code, then taking a particular object and trying to tab complete on a certain object produced by that build.  We were never a able to isolate it because it required the large program to run and it disappeared when we tried to trace it.  We thus concluded it was on the large code rather than in jpype.  

As I can't fix the problem, the best I can tell you is how to isolate the problem yourself.  Uncomment the line in `native/common/include/jpype.h` that says `//#define TRACING` and rebuild. Then try to replicate the fault. Hopefully it will die in a traced entry point so we can locate the fault quickly.  If the method that dies is only top level traceable, then simply add `TRACE_IN(<methodname>)` and `TRACE_OUT` statements until you have the specific routine traced down.  Even worse if it dies in a method that does not have a TRACE block in which case you have to make a guess and check the entry points into the _jpype module.  Then worst case, if after verifying that it isn't dying within the module, then it is an interaction based fault.  This occurs when either one of our routines failed to properly increment the reference counter resulting in memory reuse, or we passed a NULL value without setting the PyErr_ appropriately or we gave a response with the incorrect type that hit an ipython Cmodule routine that failed to check the type and made a direct access to a field.  The last one requires running a formal debugger, getting a version of python and ipython with compiler symbols and a jpype built against those versions.  (Those few steps sound pretty dreadful, so I am hoping it is found in the first step.)

I may be of further assistance if you can locate the documentation on what the heck <tab> is calling when it does its magic.  I tried unsuccessfully to find the docs when this happened last time, even going so far as trying to capture the fleeting stack trace that happened during ipython segfault to no avail.

**Comment by Thrameos** [comment]
It is possible that this crash is coming from "<tab>" running in a separate python thread.   We need to test this once the thread fix patch is in.

**Comment by Thrameos** [comment]
Though I never managed to replicate this issue a similar issues was found with unattached threads created beyond the users control.  I have revised and eliminated that issue which should fix this one.  Please verify so we can close this ticket.

**Comment by KOLANICH** [comment]
Sorry, cannot check for now, I don't have Visual Studio on my Windows machine (and if built with MinGW it crashes). Maybe after the next conda release for 32 bit Windows.

**Comment by Thrameos** [comment]
Which version of Python are you running on in cygwin?  We have a known issue with the Python 2.7 build.  My development machine is running cygwin python 3.6 and has no apparent defects.

The visual studio requirements are for the Python reference version so a full release of Visual Studio is not required.  But I understand it will take time to set up.

If you want I may be able to supply you with a binary version for windows if I know which target I need to building for.  I have miniconda and the standalone windows release versions.

**Comment by Thrameos** [comment]
The primary source of this issue was the detached threads.   This will be fixed in the next release.

**Comment by Thrameos** [comment]
Fixed in latest.  tab completion would spawn a new unattached thread which would try to access Java.  Autoattach of threads corrects this problem.

**Comment by KOLANICH** [comment]
Thanks.
