### ISSUE TITLE
Better Scala support

### ISSUE THREAD

**Issue by KOLANICH** [jpype-project/jpype#340]
1 some code for transforming some scala types into python  ones and back
```python
import re
from .JVMInitializer import *

class ScalaJVMInitializer(JVMInitializer):
	def __init__(self, classes2import):
		super().__init__(classes2import)
		self.loadScala()

	def loadScala(self):
		self.loadClasses((
			"scala.concurrent.Await",
			"scala.collection.Seq",
			"scala.concurrent.duration",
			"scala.collection.JavaConverters"
		))

		scala = self.loadClass("scala")
		self.scalaPredef = getattr(getattr(scala, "Predef$"), "MODULE$")
		self.scalaCollSeq = getattr(getattr(scala.collection, "Seq$"), "MODULE$")

	def scalaSeq(self, it):
		return self.scalaCollSeq.apply(self.scalaPredef.wrapRefArray(list(it)))
		#return self.scalaPredef.wrapRefArray(list(it))
		#return scala.collection.JavaConverters.collectionAsScalaIterable(java.util.Arrays.asList(list(it))).toSeq()

	scalaTupleRx = re.compile("^_(\\d+)$")

	@classmethod
	def scalaDetuple(cls, t):
		res = [None] * t.productArity()
		for n in dir(t):
			m = cls.scalaTupleRx.match(n)
			if m is not None:
				res[int(m.group(1)) - 1] = getattr(t, n)()
		return tuple(res)

	@staticmethod
	def getSomeKindOfImmutableObjectTemplate(cls):
		c = max(cls.class_.getConstructors(), key=lambda ct: len(ct.getParameters()))
		return OrderedDict([(str(p.getName()), None) for p in c.getParameters()])

	@classmethod
	def scalaSomeKindOfImmutableObjectToDict(cls, o, template=None):
		if template:
			d = type(template)(template)
		else:
			d = cls.getSomeKindOfImmutableObjectTemplate(o.__class__)

		for p in d.keys():
			d[p] = getattr(o, p)()
		return d

	@classmethod
	def mergeScalaSomeKindOfImmutableObjects(cls, defaultOne, *args, subMerge=None):
		res = cls.getSomeKindOfImmutableObjectTemplate(defaultOne.__class__)
		if subMerge is None:
			subMerge = {}
		scheduledSubMerges = defaultdict(list)
		defaultOne = cls.scalaSomeKindOfImmutableObjectToDict(defaultOne, res)
		res = type(defaultOne)(defaultOne)

		for i, o in enumerate(args):
			if not isinstance(o, dict):
				o = cls.scalaSomeKindOfImmutableObjectToDict(o, res)
			for k, v in o.items():
				#print(i, k, v)
				if k in subMerge:
					scheduledSubMerges[k].append(v)
				else:
					if v != defaultOne[k]:
						res[k] = v
		#print(res)
		subMerged = type(res)()
		for k in scheduledSubMerges:
			subMerged[k] = subMerge[k](*scheduledSubMerges[k])
		#print(subMerged)
		res.update(subMerged)
		vals = list(res.values())
		#print(vals)
		return args[0].__class__(*vals)
```

2 we need better support for ctors. Some ctors are not ctors and the right way to construct a class is to call apply

**Comment by Thrameos** [comment]
Does 0.7 help with this, or is there addition support needed?

**Comment by KOLANICH** [comment]
IDK how it can help. Has it introduced any scala-specific code? Because this problem is because of the way Scala uses JVM. I mean if one decompile a scala application into java code (only Krakatau has managed to decompile, everything else I had tried (jd and luyten) had failed), he really will see calls to `apply`.

**Comment by Thrameos** [comment]
Okay lets see if I can grant this wish.   Thus far you haven't provided enough information for me to go on.   To begin you didn't introduce the problem.  Something like...

> Hi, I am trying to make use of Scala with jpype.  Scala is another language that with syntax similar to Java.  It uses the same JVM but has different syntax and method name mangling.  I have a list of differences that you should be aware of  (a list of terms and other info needed so we are speaking the same language.)   What additional  information would you require to support Scala as part of jpype?

This would help because it would direct me that you are not trying to access a Java library named Scala but rather something different.  That way I am not scratching my head with "Scala ctors" ... "apply",  what is he talking about?!

So lets assume that you started there....  I would say.  "Okay it sounds like you are looking for a module ``jpype.scala``  that holds basic class types and does the name mangling.  But before we begin can you clarify a few things?

1) Are you going to put in sufficient contributions to make something like this happen?   Adding a module like that would require long term commitment on your part.  It would need to be testable using the test bench and documented.   And you would need to answer any questions that come up regarding that module.  Are you up for that?

2) Can you provide me some instructions on how to execute hello world using JPype with Scala currently?  Where do I get Scala, does it require a special path?   What is the required entry call to get it started? etc.

3) Do you have a Rosetta stone for the name mangling?  (The Rossetta stone being the famous tablet containing the same  decree in 3 languages, which is exactly what I need here.)  Something in the form of a 3 column translation.     [Scala says] -> [Java sees] -> [Python calls]  

(Making this up as I don't know)

  Scala       |     Java                 |       Python           
----------|-------------------|-----------------------
  a==b      |  a.Type_cmp$(b)  |    def __cmp__(self, a) 

4) Do you have a basic list of language defined types?  SString, SInt, SFloat, etc? 

From here I would be able to say.  "Sounds like the first step would be to define the class start up routines.   Perhaps something like `jpype.scala.SClass` similar to `jpype.JClass` entry point?  We would have to define a class customizer with `__jclass_init__` on the languages base Object type.  It would be there that you deal with all the name mangling.   And second we would need to use the customizer to define the class `__init__` method which does the Scala constructor sequence."

Last, I would point out that since JPype currently only thinks in terms of Java there are likely a lot of missing support hooks.   For example, I just finished the docstring and annotation routine for Java.  But as I was not considering that that more than one language convention would be used I coded it as a fixed entry point using JPype setResources.   Those sort of issues would need to be identified and engineered around.  All doable, but I would need instructions where ever there is conflict, because I know about as much about Scala as I know about Prolog.  (No, actually I know more Prolog as I took a class on it in 1988.)

I should note that the testing is a big issue.  In order to improve safety and stability and get this package up to "production" level I have been steadily rearranging the guts of the JPype code.  Any piece that is not covered with a fairly extensive testbench is likely to get munched pretty quickly.

**Comment by KOLANICH** [comment]
>Are you going to put in sufficient contributions to make something like this happen? Adding a module like that would require long term commitment on your part. It would need to be testable using the test bench and documented. And you would need to answer any questions that come up regarding that module. Are you up for that?

Not quite. I have some code that may be useful (I have implemented a python module using classes from a scala app and that works pretty fine and an abstration layer for that module allowing to replace JPype with GraalPython without changing app-specific code). But long term commitment and especially unit tests ... no. I really have no time for that. At least for now. I may do some rare contributions, but constant involvement into this project is unlikely. I am not a java or scala programmer, I use JPype mainly for interacting apps (currently there is only one such app, Kaitai Struct compiler) written by third-party developers, not for interacting my code written in Java.

>Can you provide me some instructions on how to execute hello world using JPype with Scala currently? Where do I get Scala

https://scala-lang.org/download/

>does it require a special path?

If you start a scala application, scala libs should be available in classpath.

>What is the required entry call to get it started? etc.

One just adds jar files in classpath and imports classes from them and uses methods from them. The difficulty is that scala constructiion of objects doesn't match java construction of objects. I have used the following algorithm:
1. decompile the target application written in Scala into eqivalent Java code using Krakatau (there is an issue here: Krakatau requires access to rt.jar and other standard library jars, but in Java 11 there is no such file).
2. find the places in the original Scala sources where this object is constructed
3. map these places to the decompiled sources (one constructing call is usually spread among different classes).
4. copy the pieces and refactor them, removing unneeded decompilation artifacts
5. rewrite the sources into python

>Do you have a Rosetta stone for the name mangling? Something in the form of a 3 column translation. [Scala says] -> [Java sees] -> [Python calls]

No. All I have is the source of my python module and the sources I have posted into this bug tracker. IMHO in order to determine it right sources of Scala compiler should be examined, but it is written is Scala itself and Scala is a bit esotheric.

>Do you have a basic list of language defined types? SString, SInt, SFloat, etc?

Not quite. I have some code (I have updated the code in the top message) and some insights.

1. in order to access Scala collections from python one needs to call `JavaConverters.asJavaCollection`
2. in order to access sequences the code from `scalaSeq` should be used
3. in order to access tuples use `scalaDetuple`
4. strings are a subclass of Java strings.
5. properties are getters and setters with the same name
6.  default functions arguments are stored as methods with esotheric names. These methods are called to construct them.  The good news is that they are usually not complex, so it may ge possible to extract the raw values and use them as default args in functions signatures.
7. sometimes in order to construct an object you need to call `apply` rather than class name
8. sometimes in order to create an instance of a class you need to prepend its name with a dollar sign

**Comment by Thrameos** [comment]
> Not quite. I have some code that may be useful (I have implemented a python module using classes from a scala app and that works pretty fine and an abstration layer for that module allowing to replace JPype with GraalPython without changing app-specific code). But long term commitment and especially unit tests ... no. I really have no time for that. At least for now. I may do some rare contributions, but constant involvement into this project is unlikely. I am not a java or scala programmer, I use JPype mainly for interacting apps (currently there is only one such app, Kaitai Struct compiler) written by third-party developers, not for interacting my code written in Java.

It would be relatively difficult for me to support this without a user willing to place a time commitment in.  To interact properly test the interactions with Java required about 400 unit tests and I am not sure that we have completely covered it.  In order to support something I am not a primary user on, I would need a test bench with similar levels of coverage.   Of course many of those tests are for basic interactions with the core but even if I assume that half the tests in jpype are core (which is a WAG) , that means on the order of 200 tests would still be needed.

Is there a community need for Scala interactions with Python?  If so are there not already alternatives?  If there is a need and no good alternatives, where would we find someone who is interested in building the required test bench?

I can certainly put in time to place low level hooks required for such an endeavor (that is sort of my niche), but I am unlikely to be able to drive it at the api level.  The only way that can determine needs for JPype are my own professional usage and the occasional Issues posting.  I am afraid without I user any attempt I make would just look half assed and not be usable.

**Comment by Thrameos** [comment]
Unfortunately I am going to close this thread due to lack of user support at present.  If you do have the time to write out a quickuse guide for Scala, write some test units, and can point me to the required technical documents we can pick this up later.
