### ISSUE TITLE
New Readme

### ISSUE THREAD

**Issue by originell** [jpype-project/jpype#396]
Our Readme is pretty.. minimalistic. 

It's time to juice it up a bit. 

Inspiration:

- [this thread](https://threadreaderapp.com/thread/921921604140937216.html)
- [prettier](https://github.com/prettier/prettier)

**Comment by Thrameos** [comment]
I took a crack at this by changing it from an "effort" to an actual library.  But it still needs some work once we get 0.7 released.

**Comment by originell** [comment]
Nice! I've been moving this TODO on my list from day to day since january.. I hope I can at least provide some solid basis for this over the next couple of days

**Comment by Thrameos** [comment]
Lets see if the $20 commission I gave my daughter to draw a white coffee cup surrounded by a blue python staring into coffee at a yellow reflection pans out for a project splash.

**Comment by Thrameos** [comment]
I think the readme should at least point to the installation instructions.

**Comment by marscher** [comment]
You're absolutely right about that.

**Comment by Thrameos** [comment]
@originell Okay I took a crack at improving the readme.  Still waiting on the art commission, something about needing to get a dress and go to middle school dance...

**Comment by originell** [comment]
amazing! I hope that Github Sponsors rolls out to every repo soon, so I can buy you peeps something for celebration!

**Comment by Thrameos** [comment]
@originell 

Okay to wrap up this discussion, lets answer the questions that started it...

> 1. Have you described what it is and what the benefits are in a way a non-developer can understand?

Given our primary appeal is as a tool for a developer, I am not sure how relevant that is for JPype.  That said our README is pretty clear on the cost benefit.

> 2. If someone Googles to try to learn more about it, is this description easy to find?

See issue #357 

We are the second link listed at https://wiki.python.org/moin/IntegratingPythonWithOtherLanguages
after Jython.  Not sure if it is just luck or maybe someone just liked us.
We are the  10th google link on the search for "java python bridge".  A web page using more keywords would draw more hits to the project.

> 3. Is this description easily skimmable? If someone looks at it for 6 seconds can they be convinced?

I believe so.  We covered all the bases of what we are and what the tool does.

> 4. Do you compare your tool to other similar tools so people feel educated about pros/cons of yours?

We only compare to Jython.  We currently do not compare to py4j, jpy, or javabridge. 

py4j - this is the most similar tool.  If I remember correctly they use a pipe based gateway function rather than the JNI interface.  I believe I rejected them for performance reasons when I joined this project. (https://www.py4j.org/)  My overall impression was they are active and professional, but not in the direction that I needed.  Their performance limits are not likely to change in the near future.

jepp - This is a reverse bridge approach.  It is directed at how to use Python from Java.  Not really a competitor currently, but perhaps something we can use should we try to add a reverse bridge into our suite.

jpy - Pretty similar to ours with the exception they are a bidirectional bridge.  They are also JNI based so performance is part of their goal.  We could state their feature list as our own directly without modification.  They are farther ahead in operating in reverse direction (we have none), but the integration level to Python appears much lower overall.  Our integrated factory based methods gives us a much slimmer API with more power.  Unfortunately, their name is very hard to google without other words (mostly gives Japanese currency information).  I rejected theirs due to some problem getting it working that may have had nothing to due with their actual library at the time.  That said JPype even at the time I started presented a more integrated appearance.  We have only widened that gap.   (https://jpy.readthedocs.io/en/latest/intro.html)

javabridge - Appears to be a remote execution type bridge very unlike our integrated approach. (https://pythonhosted.org/javabridge/hello.html) It was so far outside of my needs I didn't even stop to consider them.

Thus I would say our niche is on the highly integrated Python module in which we present Java as Python.  Performance also is a strong second on our features list.  Our limitations when comparing the competition are working with multiple JVM and Java operating Python (reverse bridge).  Both of these could be achieved, though if it compromises either of our main features it may lose value. 

> 5. If performance matters, do you have easy-to-skim benchmarks that include comparing it to other tools?

No we do not have benchmarks currently.

> 6. Do you have a demo? If it’s open source, are there well documented and easy to build samples/demos?

We are pretty light on the demo front.  Though the documentation starts with one.

> 7. Have you spoken or written about your tool? Twitter, a tech blog, online communities, meetups, conferences, podcasts, etc

Nope, we are lurkers on that front.  I will consult the skeleton of my former employee to find out why we are so far behind on that front.

> 8. Have you pitched it in 1:1 conversations with developers who might be interested?

I am hold up in a bunker deep in the national laboratory system, so 1:1 conversations aren't really my thing.

> 9. Have you talked with developers who may be interested to learn about why they haven’t tried it or 
don’t use it?

Yes.  We try to address anyone that raises an issue here that tried to use it.  Even if we can't support their needs with our current codebase, we have tried to figure out why we didn't meet the needs and add it to our roadmap.


Okay this about covers it.  The few things I see as far as relations we could do.  
1) Get that sourceforge old page pointed to here or replaced with relevant info. #357
2) Edit the contexts of https://wiki.python.org/moin/JPype  I think just a copy and paste of our readme would do.
3) Consolidate the forks.  That is something I have been reaching out on.  Most of the forks are old and dead but they can leave a bad impression as anyone that tries to use a dead fork and gets a segfault is a black eye to our new and shiny version.  The key request was that we need to provide wheels for our versions. #397 tcalmant#28
4) Consider consolidating jpy.  Superficially it appears their API can almost be replicated using our current API using a simple wrapper, if we added a reverse bridge we could possibly replace them entirely.  Not sure how active they are.  
5) Set up an actual Homepage rather that using Github as the project front.

**Comment by Thrameos** [comment]
Okay finished the logo.  I assume that works. #474

**Comment by Thrameos** [comment]
@originell So did we complete the actions required for this thread?
