### ISSUE TITLE
is it possible to unload jvm? 

### ISSUE THREAD

**Issue by robertosilviu** [jpype-project/jpype#438]
When i start JVM and then shut it down and start a new JVM the previous one still remains in memory . Is it possible to delete the previous one in some way ? Version 0.7 fix this issue ? i'm using a python package that communicates with a java application by using Jpype . This package has a method to call jpype.shutdownJVM() and shutdown the JVM which has been created for the bridge communication . My application opens and closes this bridge multiple times ( by doing that multiple JVM are started and shutdown) and when it does that makes the ram usage increase a lot . I think that the problem are the JVMs which aren't unloaded .

**Comment by marscher** [comment]
No it is not possible. At least not in any of the known JVM 
implementations.

**Comment by marscher** [comment]
@Thrameos Should we remove this function all together? This questions comes up a lot.

**Comment by Thrameos** [comment]
Well I have been in the process of fixing this one at least sort of.  We can shutdown the JVM and if you access the classes created it will say the JVM is no longer running.  All good (was much worse before).  The problem is that is you start another JVM again something weird happens.  The old objects are no longer functioning, but they are no longer alive.  Instead they are zombies which will segfault if you access them.  Further because we don't delete C++ resources (and there are a pile of them) you can do what this user has done, create, shut down, forget about all the resources, create a new one, use the new resource, shutdown, repeat.  This will leak like a sieve assuming you avoid waking up a zombie which will kill you faster than a creeper in a mine shaft.  Every copy creates another huge pile of resources and then leaks them.

Unfortunately, it isn't just this pattern.  We get the same problem if we somehow reload the jpype module itself in a way that the internal module got orphaned. 

I have on my plan to address this in 0.9.  The fix comes in several parts:
1) PyJP* object don't have a pointer to the global JVM using global handles, but rather a specific instance of a C++ object which itself a pointer to an object that holds all the resources.  This handle get passed to set up frames, use JNI methods and the like.
2) When the JVM shuts down the resource object dies and is cleaned up, and the handle to it is marked invalid.  The handle itself is managed by Python.  Further, we dump all the internal class tables and everything else that was associate with that previous JVM.  
3)  Any old object check if the current JVM they have is alive and throw if it is not.
4) A new JVM (or potentially multiple JVMs if I could manage it) can live peacefully.  The trick will be that you can have two class wrappers living in difference JVM which are themselves not equal.  Thus if you want to use JClass with a specific JVM you would need to create a class wrapper for that JVM.  ``JClass('java.lang.Object', jvm=MyJVMInstance)``.
5) Last, all of the typemanager resources need also to be tied to the particular JVM, which is scheduled to happen in version 0.8.

The problem here is some of them are a light lift but a few of them are really heavy.  Thus until I finish a big pile of other things this one is out of reach.  On other words by the time I get to this one, we will be able to do things like start CPython from within Java and use matplotlib from there.  

A secondary problem is that our documentation is leading to this question.  It specifically states that "jpype.shutdownJVM()" is a very important call.  I NEVER use it.  The default understanding of the user should be that the JVM should not be shutdown as Java resources are cleaned up on exit just like python ones.  The only UNLESS is if you really need to do clean up work that can only happen after the JVM is done, saving work, closing pipes gracefully, etc.  

I think other parts of the documentation are clear that you can't start the JVM more than once, nor can you load more than one JVM.

I think the safest thing right now (short term), would be to put a check on startJVM such that if it was already called and the JVM is not running now raise and exception that starting twice is not supported.  I don't want to run out being able to do this in the future, but we can't support it now.  Second remove references to shutdown JVM except in the API documentation with the caveat we do not support loading again.  I have the same issue with the attachToJVM.  There are no test cases for how or why to do so.  It may work, but I have no idea how to make it happen.
