### ISSUE TITLE
JPype 0.7 no longer converts java.lang.String to str automatically

### ISSUE THREAD

**Issue by kyle-downey** [jpype-project/jpype#468]
We just tried to upgrade a 0.6.3-based codebase which makes extensive use of auto-conversion from java.lang.String to str throughout the codebase, and are seeing many breaks because code assumes that java.lang.String return types will be auto-converted to str type. This feature appears to have gone away in 0.7, and although we can carefully work around it by wrapping every java.lang.String in str(), I am worried we are going to miss some instances.

This is on Python 3.7 with latest cut of 0.7.

**Comment by Thrameos** [comment]
Yeah, this was one of the difficulties we ran into.  The default behavior was switchable during runtime between autoconversion and not, with the default being to convert.  Unfortunately the global switch was rather busted, and the actually conversion code did not handle encoding.  In theory, one would set the global option at one place and then unset it, but that caused absolute havoc in the general sense that calls issued during the flag change got different behavior.  Just one person on my team switching it one way caused other modules to bust for another users module, and back and forth, so it really didn't look like a supportable option.  Thus I had to redo it.

Autoconversion by default was both inefficient and worse made it impossible to work with certain APIs like string builder as there was no way keep the string on the Java side, thus could not really be the default going forward.   I attempted to overload JString to Python string, but Python does not have any abstraction on the string class, so there was no way to duck type it at that level.  Instead I tried to make it as string like as possible, with a valid == and hash code to an actual string.  Meaning it looks like a string for printing, mapping, comparison, etc.   

However, you appear to be depending on the string being converted.  Thus that may not cut it.  

So how to fix this...

First, if you would mind position some snippets of your code, we can likely see what methods you are calling that require the return to be an actual string.  It if is something simple, then we can just add a JCustomizer to the string class to add a few methods.   For example, if you need to call the python lstrip, rstrip and strip methods on the java string, and it just isn't there because java strings don't have that method, then adding a customizer is an easy solution. 

Next, if the problem is on the return from a particular method.  Ie, you have a specific method returned from Java that should always return a Python string.  Then I can give you a pattern for adding a Customizer to that class to convert on the return.   This may also be an easy solution.

Next, assuming you neither solutions are workable, we have to consider trying to reactivate the old switch (but as a set once option).   This would be done once when the JVM is created in the first place.  It is possible to do with some work.  Most of the calls go through the same conversion routine point so it is doable.  (The only problem being all off the calls go through the same point, so it may break other parts of JPype, as we only want the conversion on the return from methods.)

```
jpype.startJVM( ....,  convert_strings=True)
```

We could also try to do it more locally.   Ie, tagging only a specific set of classes (all mypackage.*) convert strings.  Is this just on method returns or also on field gets?

**Comment by Thrameos** [comment]
I checked the code...

Type conversion goes through a method ``convertToPythonObject``.   The following code paths go through that routine.

-  Objects getStaticField
-  Objects getField
-  Objects invokeStatic
-  Objects invoke
-  Objects getArrayRange
-  Objects getArrayItem
-  Proxy calling arguments

Which code paths do you expected Python strings to appear if string conversion was to be applied?  The old version had a somewhat different control flow, so this list may not match the previous 0.6.3.

**Comment by Thrameos** [comment]
Please test with #469 to see if if fits your purpose.

**Comment by kyle-downey** [comment]
Thanks, I think #469 is good for our use case; it's hard to give a sample because it's all over the codebase: fields, constants, method return types, etc.. I need to get a build pulled in and deployed which I'll try to get done on Monday and will give it a try. Thanks!

**Comment by kyle-downey** [comment]
@Thrameos, I am seeing errors with 0.7.0 with constructors or methods not matching when passed "str" types in place of "java.lang.String" and "boolean" types. Is this expected? It works fine with 0.6.3. Note I haven't yet been able to try with your #469 fix; was just surprised to see the issue going in the other direction (str => java.lang.String) as well as on getters, fields, etc.. Will convert_string option work bi-directionally?

**Comment by Thrameos** [comment]
Sorry for the slow reply.  My email is delivered to my work address so I don't get to see things until the weekday.  

As far as I am aware, there are no known issues with string or boolean types.   It may be hitting something in the method overloading determination.  If you can generate a short example with a Java source declaring the method signature you are attempting to match and a python code that demonstrates the error, I can get in an debug it.   I know that there were some changes in the method resolution when we added improved error reporting, but nothing triggered in our test bench.

**Comment by kyle-downey** [comment]
The latest 0.7.0 cut looks good -- you can close this issue. Thanks!
