### ISSUE TITLE
JPype should populate __doc__ on exposed Java methods

### ISSUE THREAD

**Issue by kyle-downey** [jpype-project/jpype#477]
We use JPype in combination with Jupyter notebooks, and one thing we noticed is the __doc__ string is not correctly populated for Java methods; as a result the online help() function does not correctly describe the interface. It would be very useful to add this to allow proper introspection of Java interfaces in Jupyter.

**Comment by Thrameos** [comment]
Do you mean producing ``__doc__`` strings from javadoc?  If so I don't think that is currently possible.  Java does not by default compile the javadoc into the jar file.  Of course it you just mean give me a table of the signatures for the interface, that may be doable.

I tried once to just use reflection to generate ``__doc__`` to give me the types of the arguments and the overloads, but that means that the ``__doc__`` would need to act as a property so that it could be generated on demand.  Like generating the signatures #297, one just needs to figure out how to convince python to call a function that would populate it.  Assuming that we could get Python to look it up rather that trying to take the value from the slot, I can then add a new hook to ``setResource`` that would provide improved output.

I am going to place this on the requested enhancement list.  Perhaps I will give it another attempt this evening to see if it is technically possible to dynamically generate these properties.  I have gotten a bit better at tracing into CPython paths so maybe it will go more smoothly this time.  It would be very nice to have better looking docs and autocomplete.

**Comment by kyle-downey** [comment]
All we are interested in is an accurate description of the method, parameters and return type; extracting javadoc is not necessary. Ideally it should leverage / extract as much of the generic type info as possible.

**Comment by Thrameos** [comment]
Python has not made this easy.  Here is the ``__doc__`` property on types.

```
static PyObject *
type_get_doc(PyTypeObject *type, void *context)
{
    PyObject *result;
    if (!(type->tp_flags & Py_TPFLAGS_HEAPTYPE) && type->tp_doc != NULL) {
        return _PyType_GetDocFromInternalDoc(type->tp_name, type->tp_doc);
    }
    result = _PyDict_GetItemIdWithError(type->tp_dict, &PyId___doc__);
    if (result == NULL) {
        if (!PyErr_Occurred()) {
            result = Py_None;
            Py_INCREF(result);
        }
    }
    else if (Py_TYPE(result)->tp_descr_get) {
        result = Py_TYPE(result)->tp_descr_get(result, NULL,
                                               (PyObject *)type);
    }
    else {
        Py_INCREF(result);
    }
    return result;
}
```

Rather than giving a call to GetAttr, they directly consult only the slot and the hardwired dictionary slot.    Thus I will have to make a dict on methods to provide this feature.  It can be a property as they allow for descriptor.   But there is no provision to get the object instance that I see.  It is clear they never intended for an object to be able to supply a ``__doc__`` dynamically.  Perhaps it is possible to intercept the process earlier in process.

**Comment by Thrameos** [comment]
Okay I think I figured it out.   Adding the attribute ``__doc__`` to the ``tp_getset`` lets me catch the request and redirect it to another method.  Now I just need to create a resource hook and point back to python where we can generate the doc string.

**Comment by Thrameos** [comment]
@kyle-downey I assume #478 is along the lines of what you are looking for.  If you have alternative fields/formatting that you would like to see, please post it to this thread or submit a pull request.

**Comment by kyle-downey** [comment]
Hi @Thrameos this looks good -- we are going to make a cut and try it out on Monday morning and will let you know if any issues. Thanks for the quick turnaround!

**Comment by kyle-downey** [comment]
This worked well, thanks @Thrameos. We did notice two bugs in the patch:

(1) _jclass.py like 499 has a typo, variable name should be fieldInfo
(2) when a method is overloaded and has different return types, e.g. String#getBytes() is a good example because it returns both byte[] and void, the reported returns document should probably be dropped; right now it seems to just pick the first return type

**Comment by Thrameos** [comment]
The typo on line 499 was corrected in a later commit.

The behavior for mixed returns was to list all with the exception of void.  Thus if it were `byte[]` and `void` it would list just `byte[]` as the result would be "byte[]" or "None" which "byte[]" is a type of thus the documentation would be correct.  If it were `byte[]` and `int[]` it would list both.   The intention of this was to keep void from producing a return statement and as void isn't a return type but the result `None` would be.  Thus the behavior is as was intended.  The test case you selected just happened to be the corner case in which the void was dropped.

Here are examples of a few cases: 

Mixing with void gives everything but the void.
```
Java method dispatch 'getBytes' for 'java.lang.String'

  Virtual Methods:
    * void getBytes(int, int, byte[], int)
    * byte[] getBytes(java.nio.charset.Charset)
    * byte[] getBytes(java.lang.String)
    * byte[] getBytes()

  Raises:
    java.io.UnsupportedEncodingException: from java

  Returns:
    byte[]

```

Void only lists nothing.
```
Java method dispatch 'wait' for 'java.lang.String'

  Virtual Methods:
    * void wait()
    * void wait(long, int)
    * void wait(long)

  Raises:
    java.lang.InterruptedException: from java

```

Return with multiple types (except void) list all.
```
Java method dispatch 'remove' for 'java.util.Map'

  Virtual Methods:
    * java.lang.Object remove(java.lang.Object)
    * boolean remove(java.lang.Object, java.lang.Object)

  Returns:
    boolean, java.lang.Object

```

I debated trying to add a reference to the javadoc as a http link for java.lang based classes, but didn't have time to work through it.  Also if the javadoc jar for the package is in place we could link to it instead.  If you have an improvement to the doc generator, please submit a pull request.
