### ISSUE TITLE
TypeError: No matching overloads found for ... options are:

### ISSUE THREAD

**Issue by lpla** [jpype-project/jpype#505]
Hi. I am developing a Python wrapper for a Java tool ([pdf-extract](https://github.com/bitextor/pdf-extract/), wrapper is [python-pdfextract](https://github.com/bitextor/python-pdfextract)) and I am having a weird issue, where JPype cannot detect the function overload but one matches:

```
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pdfextract.extract import Extractor
>>> extractor = Extractor(pdf=b"test")
>>> extractor.getHTML()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lpla/bitextorment/lib/python3.6/site-packages/pdfextract/extract/__init__.py", line 48, in getHTML
    self.writter = ByteArrayOutputStream(self.extractor.Extract(self.reader, JString(self.language), JString(self.options), self.debug))
TypeError: No matching overloads found for com.java.app.PDFExtract.Extract(java.io.ByteArrayInputStream,java.lang.String,java.lang.String,int), options are:
        public java.io.ByteArrayOutputStream com.java.app.PDFExtract.Extract(java.io.ByteArrayInputStream,java.lang.String,java.lang.String,int) throws java.lang.Exception
        public void com.java.app.PDFExtract.Extract(java.lang.String,java.lang.String,int,java.lang.String,java.lang.String,int) throws java.lang.Exception
        public void com.java.app.PDFExtract.Extract(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,int) throws java.lang.Exception

        at findOverload(native/common/jp_method.cpp:242)
        at findOverload(native/common/jp_method.cpp:245)
        at invoke(native/common/jp_method.cpp:253)
        at __call__(native/python/pyjp_method.cpp:142)
```

**Comment by Thrameos** [comment]
Is the method static? Our error reporting on this sort of thing can be confusing, so i cant tell is your python object is an object or a class.  It seems like it should be a match, but there may be a hidden argument causing an issue.

**Comment by lpla** [comment]
This is the Python code: https://github.com/bitextor/python-pdfextract/blob/master/src/pdfextract/extract/__init__.py

And this is the Java code: https://github.com/bitextor/pdf-extract/blob/c1d9f74b47d735534eb4baed6b61713159f21193/PDFExtract/appClientModule/com/java/app/PDFExtract.java#L375

Method is not static, I call Extract public function from the instantiated object in Python (after calling JClass) and I don't see why should be any hidden argument in my call, but I may miss something.

How can I help or improve logging in JPype to try to identify the exact issue here?

**Comment by Thrameos** [comment]
Thanks.  I am currently on the road for the holiday weekend,  so I won't be able to debug it until I get back.  It seems like a problem in JPype as I do not see any reason that it should be able to hit that overload given what you have shown.

Instance called methods have a hidden first argument which should appear on the list when it shows you the match for what you passed.  If you attempt to call an instance using a static class (which is an easy mistake), then the matcher will should what appear to be perfectly valid matches because the required hidden argument is missing.  Thus I would expect that if you are not calling a static, then it should have said 

```
No matching overloads found for com.java.app.PDFExtract.Extract(com.java.app.PDFExtract, java.io.ByteArrayInputStream, java.lang.String, java.lang.String, int)
```
Thus it would seem to indicate that ``self.extractor`` is a class rather than an instance.  If that is not the case then would have to be an error in the JPype overload matcher.

I should likely improve the error messaging to display the calling flags (instance or static) on the error message so it is a bit more clear which case we are dealing with.

**Comment by Thrameos** [comment]
Actually that appears to be the case....

Your code has the line...
```
self.extractor = JClass("com.java.app.PDFExtract")
```

which means that self.extractor is a ``<Java class for com.java.app.PDFExtract>``  which is likely not what you are intending.  If you want to create an extractor you would need to call the constructor.

```
self.extractor = JClass("com.java.app.PDFExtract")()
```

Thus the error message is correct.  Your code is attempting to access an instance method as a static.

**Comment by lpla** [comment]
You are completely right. Fixed now. Thank you a lot!
