### ISSUE TITLE
JBoolean and JClass('java.lang.Boolean') map to integer

### ISSUE THREAD

**Issue by kyle-downey** [jpype-project/jpype#517]
in 0.6.3 a variable "value" of type JBoolean or JClass('java.lang.Boolean') returned false with a check "isinstance(value, int)" but in 0.7.0 this test returns true. The older behavior seems like the more correct one.

**Comment by Thrameos** [comment]
According to Python it is correct....

```
print( isinstance(True, int)) => Python2: True, Python3:True
print( isinstance(False, int)) => Python2:True, Python3:True
```

It has to do with the way that boolean was defined in Python.  It is a subtype of int. 

JPype 0.6.3 did not define any relationships between the Python types and thus be default isinstance would be False.    JPype 0.7.0 tries to follow the Python conversion rules and thus it maps to the nearest Python type.  Thus by doing so it must inherit all of the Python behaviors, including the bad ones.

There is also some special behavior going on as True, False, and None are special singleton instances, thus portions of the Python API are hard to deal with.  Though I was able to get ``issubtype(JBoolean, bool)`` to pass in Python3 at one point but had to drop it due to Python 2 problems.  But that is a much deeper discussion.

> The older behavior seems like the more correct one.

I am generally in agreement with you that this is a classic example of bad object oriented design.  Other languages like C++ and Java do not have such rules.  Given the governing principle is that we obey Python rules for Python constructs, it would seem like this is a won't fix.  Sorry.

What problem does this behavior cause in your program?  Maybe there is something else we can do to make JBoolean quack better so that you do not require this test.
