### ISSUE TITLE
Performance of python wrapping?

### ISSUE THREAD

**Issue by sylvlecl** [jpype-project/jpype#528]
We are investigating using jpype to provide python bindings to [powsybl](https://github.com/powsybl/powsybl-core) framework, a java framework aimed at electrical power system modelling and computations.

First experience is very promising, congratulations for the great job done so far ! :)

However, the main drawback we have identified so far is the performance of building python wrappers around our java objects.

**An illustrative use case:**

For example, a large electrical network may contain around 10000 "electrical buses", represented as java objects. Retrieving the list of thoses buses in python takes around 0.5s, which is a lot for our use cases :
```python
network = ...
buses = [b for b in network.getBusView().getBuses()]
```

This is easily reproduced without any framework specific jar, for example:
```python
# Create a java array list containing java objects
from java.lang import Object
from java.util import ArrayList

start = time.time()
javaList = ArrayList()
for i in range(0, 10000):
    javaList.add(Object())

print('Fill time = {}s'.format(time.time() - start))

# Gather all objects in a python list
start = time.time()
l = [javaList.get(i) for i in range(0, 10000)]
print('Get time = {}s'.format(time.time() - start))
```

This gives the following result:
```
Fill time = 0.28787922859191895s
Get time = 0.28006649017333984s
```

If we want to improve the performance or our binding, I think we are left with 2 solutions :
 - Provide in our java framework a more vector-oriented API around our core object model, which could leverage numpy support. But this may not completely suit our needs.
 - Try to improve the performance of building python wrappers in jpype ? *Do you foresee future evolutions that could improve this ?*

**A more detailed analysis:**

A C profiling with google perftools shows that for the "get" part above, less than 5% of time is actually spent in JNI calls, whereas around 60% of time is spent in `JPClass::convertToPythonObject` for java calls results, and 20% of time is spent in `JPPythonEnv::getJavaValue`.

A python profiling of the same code seems to show that this time is mainly spent in python code, notably `JObject.__init__`.

I would think that moving some of jpype python code to the C extension, for example the JObject class, could greatly improve this situation (for example, the `__javavalue__` field could be retrieved directly from the corresponding C struct instead of going through the whole "get attribute" machinery) :
do you think this could be an interesting direction to go for, or does it sound too much of a development effort (or maintainability loss...) ?

Thank you!

**Comment by Thrameos** [comment]
Lets start with the discussion on optimizing speed of calls in general and then look at this specific case.

I am currently working on trying to move more of the code into Java from the C++ layer to try to make it so that most of the code makes minimal trips across the JNI layer.   Currently, the code performance is pretty bad as it takes many trips polling for all sorts of information (basically lots of micro transactions rather one large call).  But it is a fairly slow process because there are a lots of interactions and debugging in the C++ layer can be very challenging.   Less JNI trips and more resources with definitions that java should improve performance.  And debugging the Java code is way faster as I do not have to recompile JPype to make a test, as I can just change the jar file.

I haven't done much on the Python side in terms of optimization.   The decision was made long before I joined to move as much of the logic out of C++ into Python.  A blog from the time said the cost of maintaining and debugging the C++ meant the developer was spending all his time working on C++ for what he envisioned as a Python project.   I have partially removed that decision by adding back an CPython object model rather than the capsules.   I am not sure I could move the dynamic typing system into C++ as the meta programming to make Python follow Java which would be required to negate the ``__javavalue__`` calls.  The metaprogramming to hijack Python is already pretty nasty and I don't see moving it to C as possible until we drop Python 2 entirely.  (Note the ``__javavalue__`` solution we have was added to cut down on many of those trips that the previous version had as traversing the type dict tree is slower than traversing the object dict as the type tree is one dict lookup per inheritance level.)

As to the overhead of method calls, I have yet to figure out a good solution for the performance issues on calling.   Whenever we want to call a simple function like ``List.get(int)`` we have to first resolve each overload.  That means for each call we find the list of overloads  in this case just ``List.get([List,] int)`` (the first argument is the hidden this pointer), then we have to take the list of Python objects ``PyObject(JObject), PyObject(python int)``, and find a match with each potential type to find the conversion, which would be a proxy, java object, or object with ``__javavalue__`` for the first, Then match the second python int, int quacking python object, indexable, JPrimitive, arbitrary object with ``__javavalue__`` of type int, short, byte or a boxed type with convertibility ``java.lang.Integer``.   Once we find a match we then make the call.  Each check runs either through the Python object dictionary or the Python type dictionary.  Even if I reorder these to try to make it proceed faster for one case (say move python int to the top so that we hit python int before we hit the jvalue path), when there is a list of overloads it still has to proceed through the whole list to ensure that each overload other than one to be called is a fail.  Thus shorting one path in the chain does nothing unless we get lucky and hit an exact match because of forced casting which is why the forced casting is the first thing it checks on each path.  In this case ArrayList is not exactly List, so we can't short the process without force a JObject cast which has its own overhead.   It is possible to cast once and reuse the cast thus bypassing some of the calls, but then the Python code gets pretty unreadable.

I have debated adding a series of caches to quickly realize that the same object is called in this case the list object would be checked once per call per overload.  But threading issues seems to cause serious issues on that front.  Everytime that we leave to Java, Python can change to another shared thread and thus the caches quickly become corrupt.  Adding a cache so it cuts short the overload list also is problematic as the overload list is what is imposing the Java type conversion rules.  Thus skipping it up would cause an overload to mask another where it shouldn't.  Last time I tried this I ended up trying for two weeks of debugging with nothing to show for it.

The last issue that has to be considered is bootstrapping.  Most often the reason for a particular structural pattern in the code, is that particular order is required to get the system going.  Once we have all the resources loaded the order of certain calls can be arbitrary (thus I can swap the lookup of one call for another).  But when the system is trying to load the resources then we have to call to say get the minimum integer value from Java while we don't yet have have the resource for the boxed type which is part of the concept of an integer.  Basically the system is using the fact that the path to complete will dodge the path which would use a resource is still null that the point.   Thus even simple order changes in paths tend to require 4 hours worth of debugging time.  Obviously this is something I am trying to fix as a system that is so fragile that something as simple as changing order of calls breaks everything makes find new core developers. 

Okay that about covers the issues with trying to optimize the general case.  So lets consider the alternative methods which is improving performance in a specialized case.  I have nothing at all against performance improvements and will likely add backdoors to vectorize things where I can.  In your example we could provide a backdoor to get all the items in the list using a slice operator (or just a portion).  The slice operator knows all of the items that are to be accessed in advance and needs only check the type of the object once.  Such vectorization is easy to install as a customizer on the generic container type.  Thus you would write

```
  network = ...
  buses = network.getBusView().getBuses()[0:]
```

Currently this trick works on vectors.  It was already there but I don't really like it.  By converting on a slice, we rule out left assignment thus it is currently more of an exploit than a good pattern.   I think it would be better to use something more explicit like.

```
  network = ...
  buses = network.getBusView().getBuses().tolist()
```

To make that happen, we just add a new specialized call to PyJPObject to backdoor the conversion, we add the actually JNI calls to a utility method in common, we then add the tolist() method to the java.util.List customizer.  We may also want to use a piece of Java code to convert the list to an array to save the overhead of traveling 3 times over the JNI while iterating down the list.  The only pitfall is that JNI will only allow one Java object to get pulled per call (unlike int[] where we can get a bulk transfer).  Thus as best we would make it O(N) JNI calls per pass.

**Comment by sylvlecl** [comment]
Thank you for the very quick and detailed answer :) 

Some thoughts about the general case optimization, for the moment:
moving some code to java sounds great. I can only agree that a larger c++ layer compared to the python or java layers hurts maintainability and evolutivity. Also reducing the number of JNI calls and improving method resolution sounds promising.

On the other side, profiling shows that in my simple case, the method call overhead is more the python callbacks than the JNI callbacks or the method overload resolution (I used [yep](https://github.com/fabianp/yep) which makes it easy to profile the C++ code from python) : the `JPMethodDispath::findOverload` represents 10% of samples, while `JPMethod::invoke` is 75% (mainly spent in the wrapping of result to python, and retrieving the java object from within the python wrappers). It's pretty "clear" on the call graph from the profiling but I am not able to post it here.

For those reasons, unfortunately, I do not expect major performance improvements for this use case by improving the method resolution and reducing JNI calls.

I may try to prototype something to move some of the python code to c++ if I find time in future weeks, to assess potential gains on this side, although it looks "adventurous", as your explanation underlines ... 

**Note:**
As an illustration of potential gains, I have only experimented a silly quick win : currently, when wrapping a java object resulting from a method call, one first step is to retrieve the corresponding python type. This is done by calling the python `_JClassNew` method which then returns the type cached in `_JCLASSES`. By caching this type on the c++ side instead of the python side to bypass the systematic calls to `_JClassNew`, I had a ~10% performance improvement on the code above.

**Comment by Thrameos** [comment]
Hmm.  Okay I will need to look at that portion. When you said javavalue it seemed to imply the findiverload side.

Also you should consider repeating the experiment on the 0.8 branch.  The call overhead was reduced about 40% there.  Instead of having one call decide if you can convert and then repeat the same logic to perform the conversion, 0.8 caches the result of the can convert to cut that overhead.

If the problem is on the creation of the return objects then it may be possible to accelerate.  I am moving some of that logic into the PyJP layer to support multiple JVMs.  The request for new classes for example was targetted for changes, as we cant have a unified class table when each JVM has different classes loaded.

**Comment by sylvlecl** [comment]
Actually, I performed my tests on the 0.8 branch, so I think I already benefited from the work on the call overhead (which may explain why it does not seem to be the largest overhead anymore).

I was wondering : has it already been considered an option to use a library such as [pybind11](https://github.com/pybind/pybind11) to simplify the C python extension layer code ?

**Comment by Thrameos** [comment]
I do not have much experience with pybind11.   Obviously it would add another dependency to the build, but if it helps make things easier than may be worth it.    The previous code base was really far from being about to use something like that with a 5 layer onion (native C Python, to a Python wrapper layer, to the host layer, to the C++ layer, then to the JNI binding layer).  The current code is much closer with a more traditional Python layer, a small wrapper for C++ to Python mostly to handle bookkeeping and exceptions, and then a C++ layer with most of the JNI code now integrated into the binding.  

If someone wants to remove the last separation between the Python C layer (PyJP) and the C++ layer (JP), I do not have a strong objection.  It still would be a lot of work because the Python to C++ wrapper we have is likely not compatible with pybind11.  The other complexity is the ownership of objects.  As it currently stands everything in PyJP layer has Python ownership rules and everything in JP layer has Java ownership rules.  Thus they really are very different beasts.  If we are just replacing the Python C layer (PyJP) with pybind11 it is likely not worth it.  The traditional Python C portion is a pretty small part of the code base currently and I haven't had any issues adding a new utility methods whenever they were required.   It is just cut paste an existing method with the exception handling and calling off to the C++ layer.  

The other potential downside of pybind11 is that if we do start pulling in portions of the Python code that is getting high usage, we will likely have to pull in some of the meta programming stuff that goes with it as most of the objects are dynamic.  I could very easily see us quickly hitting the limits of what the developers intended with pybind11.   But I haven't looked closely at that front.
  
@marscher should likely be the ultimate arbiter on this decision as any rewrite on that layer is likely to complete destroy the project history data as renaming and reorg of the whole native code section would be required.

**Comment by sylvlecl** [comment]
> The traditional Python C portion is a pretty small part of the code base currently and I haven't had any issues adding a new utility methods whenever they were required.

Agreed, it does not make sense to change something which works perfectly well.

I think it could only make sense to use this kind of lib if the C++ layer is to be extended, by pulling some of the python code. But then again, as you suspect, pybind11 does not support meta-programming like what is done in jpype python layer. It only supports out of the box a plain 1-to-1 mapping between c++ classes and python classes .

However, to achieve this, they use "internally" the same kind of meta-programming as jpype (with a metaclass, and one instance of this metaclass per c++ class). It might then be an idea to try to re-use some part, but "relaxing" the constraint of 1-to-1 relationship between c++ type and python type (since we will not have one c++ type per java type :) ).

**Comment by Thrameos** [comment]
The C++ layer (common) is trying to be shrunk as much as possible by making it a true JNI access layer.  That is why the typemanager and all the code used to create the resolution tables is moving to Java.  It is the C'ish layer that is likely to grow, but I think that it is not yet were I need a better extraction. 

I haven't yet had the time to repeat your profiling.  It sounds like the two objects that would most benefit are the JObject and the routine that decides a new class is required.  We would still use the same hooks, but would check the C cache before farming out the call.  This would save two calls to Python space on each return.

But before I can make the trade off first it seems like I need to do a benchmark.   I can't remove the `__javavalue__` path easily as there are a number of things hung on the ability to create any object and set this field to make it work as a Java object (mostly having to do with startup where I have create fake object wrappers while bootstrapping).  I can however, add a check prior to calling for `__javavalue__` to see it if is a `_jpype.PyJPObject` prior to fetch.  We can then add C Python objects for the critical paths which would improve the speed of creating objects.  This would speed up the call to access "this" but would add overhead as it means another search through Python inheritance tree.   Thus I should benchmark what is the cost of traversing the tree to find a type in the type list (which we do once per type we check in canConvert) and the cost of consulting the hashtable.  

Another potential speed up is we may be able to cache some of the hash keys that we are using.  If it is taking time determining the hash of the key on each call, then we can save a lot by just computing the key once and holding it as a resource.  I haven't looked into that path much, but we are certainly doing a fair amount of calls to Python hash tables that may be suboptimal.  Still this on the overload determination rather than on the return path, so maybe not the most critical right now.  The current setResource method can easily support pushing in defined object for the key.

It the tree traversal cost is high, it may be a good idea to see if we can use the internal Python search for many of types, so that rather than checking one at a time through the inheritance tree, I traverse it with a list of potential targets and return the first one that I find from the list.  I suspect that they may have a hash table for the tree check, but I have never gotten into this part of the CPython guts. 
This wouldn't help with the ones that I have to used duck typing to verify, but it would cut the overhead of some of the classes where I have a large number of specific types (oddly int and a few others have that pattern).

**Comment by Thrameos** [comment]
Okay. I replicated the speed results.  I am trying an experment with some things geared toward improving speed.  

1.  Making all Java types derive from PyJPValue directly.  This eliminates many lookups on a call.  It also cuts the number of objects in half.
2. Remove all init methods in the class tree.  Every call to init was another set of heavy python calls.  Instead all init behavior is on new which is only called from Python originated code rather the return paths.  
3. Make PyJPArray and PyJPClass both extend from PyJPValue.  This eliminates many objects.
4. Cache the wrapper types in the c++ layer so that repeat return type calls pay no lookup costs.  

All sound great but there are about 500 things that would have to happen to complete that level of work.  About 30% of the code base has to be touched do to dependencies.  And there are several cyclic referencing loops that will result that have to be dealt with.

Bootstrapping it is a mess as I need to create Object before Class but the inheritance requires the other order.  Meaning the Python class for java.lang.Class does not even exist when we need to create the first object of its type.  This was dodged previously because the objects were in two parts.  Thus I must promote objects after creation by overriding the class pointer using type hackering. 

Making the private classes a base type exposes machinery that i will need to alter the dir behavior to hide. Thus another api that i do not know.
 
Last boxed types are a mess because the underlaying multiinheritance is not possible, so i will need to fake it.  Thus i will meed to implement the number api to make them play nice.

The added difficulty is that Python API docs are very thin on this topic.  They dont even show how to use custom slots or other useful info like how heap types should work.  (Not to mention the test code in python code base shows them doing stuff that leads to negative refcnt)  So i have to discover each by reverse engineering and source browsing. 

The other requirement for this change is Python 2 support will have to die.  Supporting this type hacking on two different object systems is very difficult.

**Comment by sylvlecl** [comment]
Thanks a lot for having pushed the effort and the investigation further. Implementing all this would really look like an overwhelming task.
We are anyway still planning using jpype to provide python bindings for our frawework.

**Comment by Thrameos** [comment]
It can be a bit overwhelming.  I try to take in one piece at at a time with 2-4 hours per night. 
I am still estimating about 2 man weeks on this one just to get the point to test it.

Thus far in this pass...
- [X] Make Java object types derive from PyJPValue directly. 
- [X] Introduce PyJPValueBase to interfaces.
- [X] Introduce PyJPValueException for Exception types.
- [X] Introduce PyJPValueInt for Boxed types.
- [X] Introduce PyJPValueDouble for Boxed types.
- [X] Introduce PyJPClassMeta to hold ``__isinstance__``, ``__get__``, and ``__set__`` for JClass.
- [X] Move JClass and JObject getter search patterns to C layer for speed.
- [X] Remove all init methods in the class tree. 
- [X] Rework all types to be HeapTypes so that they can have methods installed from Python side.  This is a weird Python restriction in that static types can't have dictionaries altered, but heap types don't have this restriction, thus switching to heap types makes the process easier to progress in steps.
- [X] Rework Primitives so that they are neutral to the JVM (needed to support multiple JVMs in the future)
- [ ] Introduce ``__isinstance__`` in PyJPClassMeta to check Java inheritance rather than using Python tree to reduce the levels. 
- [ ] Make JInterface a virtual inheritance enforced by PyJPClassMeta.
- [ ] Make JObject a virtual inheritance enforced by PyJPClassMeta.
- [ ] Make JString a virtual inheritance enforced by PyJPClassMeta.
- [ ] Make JException a virtual inheritance enforced by PyJPClassMeta.
- [ ] Rework customizers for new tree formulation.
- [ ] Rework JClassFactory for type splits on Interface, Object, Exception, and Boxed.
- [X] Make PyJPArray  extend from PyJPValue. 
- [X] Make PyJPClass  extend from PyJPValue. 
- [X] Make PyJPField  extend from PyJPValue. 
- [X] Cache the wrapper types in the c++ layer so that repeat return type calls pay no lookup costs.
- [X] Use ``__mro__`` list to do fast checked for different value types so that we don't have to dig through the type tree.
- [ ] Get the code to compile again.
- [ ] Remove dead python code.
- [ ] Clean up issues introduced by tree reorganization.
- [ ] Remove dead Python 2 C code as this object model is Python 3 only.

**Comment by Thrameos** [comment]
Still slashing my way through the jungle on this one.  Every time I get things back together enough to get it to compile I discover yet another interdependency between the Python layer and C layer that required another 2 hours of study, rereading the CPython API docs and source code, and then implementation.  In theory each pass through should be one less to go, but often the well is much deeper than even I know.  

Long ago in a distant blog post, the author of this particular tool decided he was tired of coding in C++ for what was supposed to be his Python project, so he pushed everything into as slim of a C API as he could muster with just a handful of module level calls using Capsules and pulling as much logic as he could to the Python layer.  (see [Oct 30, 2006](http://jpype.blogspot.com/).)   I reversed that decision along with a fleet of other ones.  I decomposed the internal interfaces back into something resembling set of classes and reformed the C++ organization to match the underlying Java machine which is where we stand in 0.7 series. 

But fundamentally there is still two of everything. There is the stuff seen by the Python programmer and the stuff exposing the Java behavior.  Unifying them would increase speed and save memory, but it also means implementing every one of the things missing for the Java classes to be viewed as Python on the API either directly in C or by pushing Python code back as hooks.  Hooks are a good way of striking the balance.  We have all of the basic pathways in C for speed, but if we hit something exotic or boilerplate in terms of a requirement, we just implement that portion in Python and install it in the extension class.  Easy in theory.

But Python types that are static can't accept hooks directly, so that means another new entry point and a new front end to redirect to the hook.  That meant either an hour installing the new hook point and then 4 hours debugging it as every change in C requires recompiling the whole package from scratch on a virtual linux box running on a 5 year old ultra low mass laptop.   To cut the time, I am switching the whole thing to heap types which is a better API (but only supported in Python 3).   That removes the Python code that was adding the hook in place of a simple assignment, removes the resource hook installer, and then removes the code that routed the C call to the hook.  Sometimes the dependency requires not just support in the C layer, but something in the C++ or Java library backend.  This would have been prohibitive in JPype 0.6 framework, but is pretty doable now (10 minutes per rather than 2-4 hours).  I greatly speed up development time by pushing logic from C++ back into Java for 0.8 series, but your request is towards the one part this is not well developed yet.  

Further I am doing all this on the bleeding edge, I have to resolve everything else that I am working on at the time.  I am trying to do this as part of the larger middle layer rework which has goals of 

- Terminate all remaining global variables.  (killed another 30 last night,  last one left is s_InterpreterState using in the thread locking)
- Break the dependencies such that we can run more than one JVM at a time or start and stop the JVM freely. (Not clear if this is even possible, but it is part of killing globals.)
- Clean up exception reporting.
- Add customization to type conversion and method resolution process so that we can trivially support integration with Python types.

I assume that when I finally wander out of the jungle, it will all be sunshine and rainbows, but in the meantime it is very dark places in terms of stale or minimum documentation, completely undocumented CPython behavior, and segfaults lurking behind every bush.

**Comment by Thrameos** [comment]
Still progressing on this task.  I am trying to get the module test harness running so that I can debug each of the new entry points.    In the original design, a java object is defined as any Python object which contains a ``__javavalue__`` which points to a ``PyJPValue``.   These values point to a ``JPClass`` which defines the behavior of the value and a jvalue union.   This allows Exceptions, Long, and Float to be mixed as needed.

Making a ``PyJPValue`` the base class instead of ``object`` means that those sort of mixins are no longer possible.  Thus each mixin type must be specifically created in the C code.  Thus I need 2 different base types and 6 specializations.  These are


  *   ``PyJPValueBase`` which has the same behavior as before in which the class type is expected to hold ``__javaclass__`` which is a java.lang.Class instance and has a ``__javavalue__`` field which holds the jvalue.
  *   ``PyJPValue`` is derived from ``PyJPValueBase`` but contains the jvalue as part of itself.
  *   ``PyJPValueExc`` which is the combination of ``PyJPValueBase`` and Python exception to serve as base for java.lang.Throwable instances.
  *   ``PyJPValueLong`` which is a combination of ``PyJPValueBase`` and Python long to serve as the base for integer box types of different lengths.
  *   ``PyJPValueFloat`` which is a combination of ``PyJPValueBase`` and Python float to serve as the base for floating point boxed types.
  *   ``PyJPClass`` which is derived from ``PyJPValue`` when specializing for a java.lang.Class instance.
  *   ``PyJPArray`` which is derived from ``PyJPValue`` when specializing for a Java array instance.
  *   ``PyJPField`` which is derived from ``PyJPValue`` when specializing for a java.lang.reflect.Field.

Into these classes I need to instantiate jvalue primitives, jvalue object with various specializations, exception types, and then boxed types.  The one total odd ball is JChar and java.lang.Character as this is not an integer type and has no real mapping in Python. I will have to work through that one last.

To keep this a reasonable sized problem, I have made most of the ``PyJPValueBase`` methods agnostic of the type so that it first resolves the location of the jvalue (either external or internal) and then proceeds, but not every entry point is able to do that.  There is also the added complexity object lifetime.  During operation everything is pretty easy, but I also need to consider startup, shutdown and post shutdown behaviors.  Because Java is controlling the lifetimes of all Java objects, that means each entry point needs to test the JVM is currently in a live state before proceeding to access the resource.  This has two edge cases.  If I force checking on access then during start up I generate access exceptions while we are creating the initial objects.  (Worked through that whole mess on Friday).  But this also causes problems with primitives which technically don’t live on the JVM, thus I need to make sure every code path checks if it is working with a primitive first before deciding if it should fail. (which was most of Sunday).   A secondary issue that I need to resolve is the reference counting.  Python and Java have different management systems.  For Java we need to create stack frames around every code path (with the exception of primitives) and with Python we need to test the reference count before and after each procedure to make sure the count before and after is correct.  The safest for Java is always create a stack frame (even when you don’t know you are going to use it).  Thus ensures that nothing can leak.  But then primitives end up with funny behaviors.  For Python I end up adding testing macros or other monitoring techniques.  It is easy to see when the reference counter has under counted as it segfaults (though often not is a meaningful place), but I also have to find the over references which I can only detect by a macro or a test code repeatedly calling an entry point and watching for the reference counter end up too high.

Unfortunately given the number to types means that I have a lot of entry points to test.  Where the old classes were behind the scenes, these are now up front and exposed, so I have to treat each as subject to user abuse.  To do this I construct a ``jpype`` mock up which pretends to be the hooks for the internal module.  This allows me to exercise each entry point an each potential failure mode separately including in conditions that do not normally occur when operated through the standard jpype wrappers.  Although it is unlikely that we will can get something as messed up as ``PyJPClass`` object calling a ``PyJPValueBase`` method during normal operations, each of these cases needs to be tested to ensure they all result in a well defined behavior.  If something results in a segfault then I have to refactor everything that touches that path and restart the testing from scratch.

I do not have to resolve every possible combination before I get some results.  In theory I can try to run your test on the mock ``jpype`` module to see what is the potential payoff of this refactoring work, but that would be subject to a lot of interpretation as it is not clear what code must remain in place when I am done.

**Comment by Thrameos** [comment]
Still making progress (slowly).  Portions of the test bench are finally starting to work for simple things like objects, methods, fields, and arrays.  But that means I need to debug introduced types like PyJPException, PyJPLong, PyJPFloat.    

Unfortunately, this is where things really get challenging, as I have a few segfaults in pure python code (such as PyObject_ClearWeakRefs).  Those are always the time consuming as I don't usually have a good way of recompiling Python with further diagnostics.  (About the only thing worse is an object reference going wrong during multithreaded code.)  It is clearly something not being set right in the type system, but I will struggle with figuring out the location until I can get some insight (usually by reading CPython sources for a few hours).

**Comment by Thrameos** [comment]
Okay work is completed.  I did a simple benchmark test on JPype 0.7.0, JPype 0.8.0a1 before speed rework, and JPype 0.8.0a2 after rework.   Each test ran 1M operations and tests were repeated 5 times.  Code is stored in classhints pull request.

Code | Op | Time | Speed | Relative
-- | -- | -- | -- | --
Jpype 0.7.0 | Fill | 7.4418 | 134375 | 0.0%
Jpype 0.8.0a1 | Fill | 8.8226 | 113346 | -15.7%
Jpype 0.8.0a2 | Fill | 2.3772 | 420671 | 213.1%
Jpype 0.7.0 | Get | 11.2606 | 88805 | 0.0%
Jpype 0.8.0a1 | Get | 10.1948 | 98090 | 10.5%
Jpype 0.8.0a2 | Get | 3.0043 | 332851 | 274.8%

That is about the limit of my speed up ideas.  All Python code is removed from primary object creation, method resolution, and return paths.  I applied MRO hacks to speed up instance checks and minimized the number of dictionary searches.

Benchmarking code

```
import time
import jpype
import jpype.imports
jpype.startJVM(convertStrings=False)

# Create a java array list containing java objects
from java.lang import Object
from java.util import ArrayList

start = time.time()
for j in range(10):
    javaList = ArrayList()
    for i in range(0, 100000):
            javaList.add(Object())

print('Fill time = {}s'.format(time.time() - start))

# Gather all objects in a python list
start = time.time()
for j in range(0,10):
    l = [javaList.get(i) for i in range(0, 100000)]
print('Get time = {}s'.format(time.time() - start))
```

**Comment by marscher** [comment]
These are really impressive numbers!

**Comment by parachute-impertinent** [comment]
> Okay work is completed. I did a simple benchmark test on JPype 0.7.0, JPype 0.8.0a1 before speed rework, and JPype 0.8.0a2 after rework. Each test ran 1M operations and tests were repeated 5 times. Code is stored in classhints pull request.
> 
> Code	Op	Time	Speed	Relative
> Jpype 0.7.0	Fill	7.4418	134375	0.0%
> Jpype 0.8.0a1	Fill	8.8226	113346	-15.7%
> Jpype 0.8.0a2	Fill	2.3772	420671	213.1%
> Jpype 0.7.0	Get	11.2606	88805	0.0%
> Jpype 0.8.0a1	Get	10.1948	98090	10.5%
> Jpype 0.8.0a2	Get	3.0043	332851	274.8%
> That is about the limit of my speed up ideas. All Python code is removed from primary object creation, method resolution, and return paths. I applied MRO hacks to speed up instance checks and minimized the number of dictionary searches.
> 
> Benchmarking code
> 
> ```
> import time
> import jpype
> import jpype.imports
> jpype.startJVM(convertStrings=False)
> 
> # Create a java array list containing java objects
> from java.lang import Object
> from java.util import ArrayList
> 
> start = time.time()
> for j in range(10):
>     javaList = ArrayList()
>     for i in range(0, 100000):
>             javaList.add(Object())
> 
> print('Fill time = {}s'.format(time.time() - start))
> 
> # Gather all objects in a python list
> start = time.time()
> for j in range(0,10):
>     l = [javaList.get(i) for i in range(0, 100000)]
> print('Get time = {}s'.format(time.time() - start))
> ```





https://willamliberation7.github.io/ng4sOojuygsalYJtsiCOSSXTVLzMNlGLenXMpHh/
