### ISSUE TITLE
version of java

### ISSUE THREAD

**Issue by Freakwill** [jpype-project/jpype#532]
I have the latest version of java. But jpype requests java SE 6 as default version when running `startJVM`. It alerts me to install java SE 6 from a website in a dialogue-box. Can I use the installed java instead of downloading a new one?

$ java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment (build 13+33)
OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)

PS: my system is macOS 10.13.6

**Comment by Thrameos** [comment]
It sounds like some sore of interaction between the stubs on your os and jpype.  Jpype is definitely not making a request for Java 6.  It wouldn’t even run with Java 6 because the jars in JPype are build for Java 7 or later.  Most likely calling for Java is hitting a stub which says the default Java in the path is “install java SE 6”.

I recommend that you set your JAVA_HOME environment variable to the appropriate location and it should run fine.

**Comment by Freakwill** [comment]
> It sounds like some sore of interaction between the stubs on your os and jpype. Jpype is definitely not making a request for Java 6. It wouldn’t even run with Java 6 because the jars in JPype are build for Java 7 or later. Most likely calling for Java is hitting a stub which says the default Java in the path is “install java SE 6”. I recommend that you set your JAVA_HOME environment variable to the appropriate location and it should run fine.

Thank you very much. I found the stub
```python
    def _pre_vm7_path(self):
        """
        Returns the previous constant JVM library path:
        '/System/Library/Frameworks/JavaVM.framework/JavaVM'
        """
        return '/System/Library/Frameworks/JavaVM.framework/JavaVM'
```
`/System/Library/Frameworks/JavaVM.framework/JavaVM` is a link, link to a JavaVM (`/System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM`) but the executable file does not work probably. I will re-link it to my java, instead  of correcting the source code.
