### ISSUE TITLE
numpy no longer optional

### ISSUE THREAD

**Issue by gganssauge** [jpype-project/jpype#569]
In recent builds of my project I noticed that another wheel is pulled off pypi.
It used to be JPype1-0.7.1-cp37-cp37m-linux_x86_64.whl but starting this year it is JPype1-0.7.1-cp37-cp37m-manylinux1_x86_64.whl (note: version is still 0.7.1).

i used not to install the numpy extra and went fine with it. The new wheel doesn't run without numpy anymore, even though I still don't install the extra, and my build started failing.

When I require the numpy extra my build starts working again.

I would propose to either no longer use numpy at all (as suggested in another issue) or make it optional again.

**Comment by Thrameos** [comment]
numpy is a bit of a problem for several reasons.  We use numpy only as a way to provide slices for arrays.  Without it slicing generates very inefficient python lists of items which effectively makes JPype unsuitable for use in scientific code.  

At least as far as I am aware we can't easily publish both binary with and without numpy version.  This poses a problem as without numpy is very poor for certain types of scientific software and with numpy is forcing a large dependency which people don't want.   Numpy is extra in that it is not required to build from source, but when we build binaries we have to choose to include or exclude it.  Because the numpy symbols are hard linked into the binary in it can't really be selected once JPype icompiled. I looked to see if there is a pip from source option, but I don't see it.  Even then from source means requiring ant and a jdk which is a bad option for many users.

I am working to resolve the issue permanently by implementing a slice API which serves the same function as numpy (slice access, memory buffer transfer, integration into numpy) without actually installing numpy.  However, that is not likely to be incorporated until JPype 0.8.0 and it will break potentially break code as the slice operator will become left assignable which is not true new because of the numpy/list copy.  But that is a way off in the future so perhaps the maintainer can weigh in with a solution.

**Comment by gganssauge** [comment]
I'm absolutely fine with my workaround (altough I'd really like to get rid of numpy).
My main problem was that the wheel changed without the version number changing.

**Comment by Thrameos** [comment]
I will make the numpy go away in 0.7.3 if possible.  See Thrameos/jpype#42

The key issue is by removing numpy we have to fully implement PyObject_GetBuffer/PyBuffer_Release to push out data and accept incoming buffers with the same.  But the buffer API is a monster with dozens of flags and many more datatypes (little/big, types) etc.  Some of the easy cases are doable, but implementing the full API including type conversions during iteration is a heavy lift.  There has to be some assistance APIs somewhere in Python to make this manageable but thus far I haven't located any.  I am currently reading the numpy sources to see if I can get enlightenment as to how to handle it without having to port the whole array concept over.
