### ISSUE TITLE
Segfault/fatal RuntimeError with 0.7.2 and numpy

### ISSUE THREAD

**Issue by khaeru** [jpype-project/jpype#630]
After CI for our project [iiasa/ixmp](https://github.com/iiasa/ixmp) started building against JPype1 version 0.7.2, both via PyPI and Anaconda, we encountered frequent segfaults. These seem to occur when numpy code (via pandas) is dealing with exceptions raised from JPype, and produce messages like:
```
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: java.lang.ArrayIndexOutOfBoundsException</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: RuntimeError</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: RuntimeError</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: java.lang.ArrayIndexOutOfBoundsException</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
```

A full log is attached: [pytest.log](https://github.com/jpype-project/jpype/files/4344306/pytest.log)

This is a regression, because the exceptions seemed to have been successfully caught/handled in numpy, pandas, or our code with JPype1 version 0.7.1 and earlier. (our mitigation is to pin to JPype1 version 0.7.1 for CI.) Now, they are fatal and the tests fail.

Unfortunately the Java code underlying our Python is in a private repo. I'm happy to copy snippets if needed or run anything to help debug. However, from lines like the following in the tracebacks, perhaps it will be possible for you to reproduce the problem without that.
```
        try:
>           return a.ndim
E           AttributeError: 'java.lang.String[]' object has no attribute 'ndim'
```
…i.e. maybe create a java.lang.String and then try to get a non-existent attribute in Python.

**Comment by Thrameos** [comment]
Thanks for the bug report.   The majority of the report may have been addressed with #611.  If it is not currently fixed by the current master.    Sorry about that a bug in our coverage matrix allowed a change which imposed some unnecessary conditions to exceptions.  I am hoping it is now fixed (we will release once we finish up our rework of the coverage matrix).  

If it is not addressed by master, please try to produce a code snippet that replicates the problem so that I can deal with it tonight.

**Comment by khaeru** [comment]
Sorry, to be clear—we did notice #611, and the log above was generated after installing from `master`:
```
$ pip install --user --upgrade git+https://github.com/jpype-project/jpype#egg=jpype1
```

I will try now to produce a snippet.

**Comment by Thrameos** [comment]
Thanks very much.  I will await the snippet.

**Comment by khaeru** [comment]
Seems to occur with length-0 arrays:
```
import jpype
import numpy as np

jpype.startJVM(convertStrings=False)

arr = []

try:
    print(np.array(arr))
except Exception as e:
    print(f'Caught {e}, continuing')
else:
    print('No exception raised.')

arr = jpype.JArray(jpype.JString, 1)(0)

try:
    np.array(arr)
except Exception as e:
    print(f'Caught {e}, continuing')

print('Done.')
```

```
$ python3 gh_630.py
[]
No exception raised.
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: java.lang.ArrayIndexOutOfBoundsException</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: RuntimeError</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: RuntimeError</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
<M>unknown : Fatal error in exception handling</M>
<M>unknown : Handling: java.lang.ArrayIndexOutOfBoundsException
</M>
<M>unknown : Type: 0</M>
<M>unknown : Inner Python: java.lang.ArrayIndexOutOfBoundsException</M>
<M>unknown : native/python/jp_pythontypes.cpp JPPyObject 29</M>
Caught Fatal error occurred, continuing
Done.
```

**Comment by Thrameos** [comment]
Excellent.   I should be able to address that fairly quickly.   I do not see any tests in our test bench for zero length arrays.

**Comment by Thrameos** [comment]
Oh fun one.   This looks like 3 bugs in one so I am going to have to fix each of them.

1) The np.array call issued a getBuffer request to JPype on an object type which is not a supported operation so it should have just sent Buffer not supported but it instead fell back to asking Java.
2) Having failed to realize it was not support it called Java to try to get a collection which should have failed with null so we can gracefully exits, but instead it throws an exception which does not map to the required BufferError type..
3) The exception is hitting some unexpected error condition (likely because we are tossing an Java exception type rather than the expected BufferError) sending Python into a panic state and triggering a random fatal exception handling routine.  (It may actually be a home run with 4 bugs in one but I have to get under the hood and poke it some more.)

So one is a 5 minute fix to tell Java typemanager to send a flag at creation time and we test it when the buffer request starts starts.   Two is about 15 minutes to figure out how it responded poorly, because this may not be only way it can hit that case so we have to be sure that it is safe.  And three is a dozy because well it is exceptions and no one ever expects them to be easy.

**Comment by Thrameos** [comment]
And as expected one hour in the future me has completed the task.  I will give you the home run on that one.  It triggered three different errors in JPype and one in numpy.  Apparently nothing checks to see if a getBuffer was misbehaving and threw the wrong exception type.  So instead of clearing the error it in numpy instead started the Python call with the error already set sending our exception handling routine into flaming death.

**Comment by khaeru** [comment]
> flaming death

:fire::skull_and_crossbones: 

Wow, looks like we stumbled on a hornet's nest! Thanks so much for untangling these—which would have been totally beyond us—and so quickly as well. I left a comment on the PR.

**Comment by pelson** [comment]
Just stumbled on this myself. My simple case was:

```
$ python
>>> import jpype as jp
>>> jp.startJVM()
>>> a1x0 = jp.JArray(jp.JDouble, 2)([[]])
>>> type(a1x0[0][0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: array index out of bounds
>>> type(a1x0[0])
<java class 'double[]'>

>>> import numpy as np
>>> np.array(a1x0)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc6a5b2a570, pid=15752, tid=0x00007fc6a7978740
#
# JRE version: OpenJDK Runtime Environment (8.0_152-b12) (build 1.8.0_152-release-1056-b12)
# Java VM: OpenJDK 64-Bit Server VM (25.152-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [_jpype.cpython-38-x86_64-linux-gnu.so+0x60570]  JPypeTracer::trace1(char const*)+0x1a0
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

```

Looks like some good tests were added in #633 that cover this. :+1: 
Confirming fixed on master.
