### ISSUE TITLE
Python references passed to the Java side for callbacks

### ISSUE THREAD

**Issue by apatrida** [jpype-project/jpype#631]
I have been using py4j and I build a custom reference system that allows Python objects to be returned to the Java side, and then passed back to Python.  Basically any Python object is wrapped which creates a UUID and adds it to a reference dict, and the Java side then holds this reference in a generic class (so that it is self-documenting about what it holds), and it can pass the reference back which is unwrapped into the original object.  By implementing `Closeable` on the Java side a resource try/finally block can protect that it is not leaking.

How would I do something similar in jpype?  Do I need to build the same model for it, or does it handle references already?  I see no mention of it so far in the docs.

**Comment by apatrida** [comment]
Example Python side:

```python
from typing import TypeVar, Generic

T = TypeVar('T')

referenceDict = dict()

class WrappedObject(Generic[T]):
    class Java:
        implements = ["ai.deem.client.challenge.term.prompttoolkit.PythonReference"]

    def __init__(self, objUuid: str):
        self.objUuid = objUuid

    def getUuid(self):
        return self.objUuid

    def close(self):
        release(self)


def wrap(obj):
    objUuid = str(uuid.uuid4())
    referenceDict[objUuid] = obj
    return WrappedObject(objUuid)


def release(obj):
    if obj is None:
        return
    referenceDict.pop(obj.getUuid())


def unwrap(obj: WrappedObject[T]) -> T:
    if obj is None:
        return None
    return referenceDict[obj.getUuid()]
```

and a Python class using it to return a value:

```python
class PromptToolkitStyleRoot(object):
    class Java:
        implements = ["prompttoolkit.PromptToolkitStyleRoot"]

    def __init__(self):
        pass

    def html(self, html) -> WrappedObject:
        return wrap(HTML(html))

    def styleFromMap(self, styleMap) -> WrappedObject[Style]:
        return wrap(Style.from_dict(styleMap))
```

and one receiving it from a Java call:

```python
class PromptToolkitOutputRoot(object):
    class Java:
        implements = ["prompttoolkit.PromptToolkitOutputRoot"]

    def __init__(self):
        pass

    def print(self, message: str, style: WrappedObject[Style]):
        printft(message, end="", style=unwrap(style))

    def println(self, message: str, style: WrappedObject[Style]):
        printft(message, style=unwrap(style))

    def printHtml(self, htmlMessage: str, style: WrappedObject[Style]):
        printft(HTML(htmlMessage), end="", style=unwrap(style))

    def printlnHtml(self, htmlMessage: str, style: WrappedObject[Style]):
        printft(HTML(htmlMessage), style=unwrap(style))
```

You can see the wrapping/unwrapping there.

Then in Java side (or this case Kotlin), you can see it used here:

```kotlin
interface PythonReference<T> : Closeable {
    override fun close()
    fun getUuid(): String
}

interface PromptToolkitStyleRoot {
    fun html(html: String): PythonReference<HTML>
    fun styleFromMap(styleMap: Map<String, String>): PythonReference<Style>
}

interface PromptToolkitOutputRoot {
    fun print(message: String, style: PythonReference<Style>? = null)
    fun println(message: String, style: PythonReference<Style>? = null)
    fun printHtml(htmlMessage: String, style: PythonReference<Style>? = null)
    fun printlnHtml(htmlMessage: String, style: PythonReference<Style>? = null)
}

// fake types to act as documentation in PythonReference usages
typealias PythonAny = Any
typealias Style = PythonAny
typealias HTML = PythonAny
```

So it is typesafe on both sides in that the Kotlin/Java side only allows the correct reference types to be used between different functions.  And the Python side unwraps to a typed object as well.

The downside so far, is the `getUuid()` call round-tripping from python to java to python when something is used.  Solution would be to have the string value passed as a field instead of via the function, but I think that is still proxied in Py4j and does the same round trip, but maybe primitives can be copied by annotating them instead of proxied to the getter?

Anyways, looking for what is the best way in JPype, if not just porting this same model.

**Comment by apatrida** [comment]
Oh, and an example using it with resource protection to prevent (or lower risk of) leaks:

```kotlin
       val globalStyleMap = hashMapOf(
            "header" to "ansibrightcyan",
            "text" to    "#DADADA",
            "subtext" to "#A3A3A3",
            "dim" to     "#555555",
            "action" to  "ansibrightgreen",
            "info" to    "#EEEEEE",
            "warn" to    "ansiyellow",
            "error" to  "ansibrightred",
            "callout" to "#FFFFFF bold",
            "button.focused" to "fg:#FFFFFF bold bg:#003900"
        )

        kptk.style.styleFromMap(globalStyleMap).use { globalStyles ->

            val htmlMessage = "<text>this text <callout>is bold</callout> and some <u>is underlined</u>!</text> <dim>and then there was this!</dim>"
            kptk.output.printlnHtml(htmlMessage, globalStyles)
            kptk.output.printlnHtml(htmlMessage)
        }        

```

**Comment by Thrameos** [comment]
We can currently pass Python objects that use ``@JImplements`` to implement a Java interface to Java and have them return to Python as their original object.  This will be extended to any Python object fairly shortly.  

The system works by attaching  a long value and then attaching a reference which is held by Java.  When the wrapper is seen by Python coming from Java it looks up the long and then pulls it back to  Python object.  I can push out some of my testing code if you want to play with it.

**Comment by apatrida** [comment]
Thanks @Thrameos, that would work.  I can make just a marker interface that represents the "type" that I want it known by even if it has no methods.  And then round trip it that way.  Sounds great!

**Comment by apatrida** [comment]
I don't need to have all methods of the Python class present in the interface correct?  It can be empty just to trigger this mechanism?  (which is good, the interface will help document the type being returned and make the round trip type safe)

**Comment by Thrameos** [comment]
Here is a quick example.

```
import jpype
from jpype.types import *
from jpype import JOverride, JImplements, JConversion

jpype.startJVM(classpath=['test/classes', 'project/jpype_java/dist/*'])

@JImplements("java.io.Serializable")
class MyObject(object):
    def __init__(self, data):
        self.data = data

myobj = MyObject("Mooo!")

# Send to Java by casting to Java
jobj = JObject(myobj)

print(type(myobj))
print(type(jobj))

# and come back again by putting into Java and getting it back
ja = JArray(JObject)([jobj])
back = ja[0]
print(type(back))
print(back.data)
```

The problem being that you can't send anything that doesn't have an interface.   Serializable can of course go into any Object so if you want to tag object then no new code is required. 

Like many things in our system often it is so simple to do that it is hard to write any meaningful documentation that doesn't look like just do this and it will work.

**Comment by Thrameos** [comment]
If you don't want to implement the interface methods then you would need to use the older JProxy method.  Of course if it calls a method that isn't implemented it will throw an exception.

**Comment by apatrida** [comment]
Thanks @Thrameos , I will have extra methods in the Python side ignored in the interface, because the interface will be like Serializable and just a marker that is empty.  This should work, so I'll give it a shot.  thanks!

**Comment by apatrida** [comment]
One issue with this approach is if I don't control the classes I'll still have to wrap them with a wrapper to add the interface, but it'll still be better than my original approach. 

When you have "all objects converted back" as you mentioned, that'll remove the need to wrap.

**Comment by Thrameos** [comment]
We can apply a patch that would permit any object to make it through a Java interface.

```
diff --git a/native/common/jp_proxy.cpp b/native/common/jp_proxy.cpp
index 24ece9c..9bd23c1 100644
--- a/native/common/jp_proxy.cpp
+++ b/native/common/jp_proxy.cpp
@@ -265,8 +265,10 @@ JPPyObject JPProxyType::convertToPythonObject(JPJavaFrame& frame, jvalue val)
        JP_TRACE_IN("JPProxyType::convertToPythonObject");
        jobject ih = frame.CallStaticObjectMethodA(m_ProxyClass.get(),
                        m_GetInvocationHandlerID, &val);
-       PyObject *target = (PyObject*) frame.GetLongField(ih, m_InstanceID);
+       PyJPProxy *target = (PyJPProxy*) frame.GetLongField(ih, m_InstanceID);
+       if (target->m_Target != Py_None)
+               return JPPyObject(JPPyRef::_use, target->m_Target);
        JP_TRACE("Target", target);
-       return JPPyObject(JPPyRef::_use, target);
+       return JPPyObject(JPPyRef::_use, (PyObject*) target);
        JP_TRACE_OUT;
 }
```

Then we can send any python object to any Java interface with.
```
# Not a JPype proxy
class MyObject(object):
    def __init__(self, data):
        self.data = data
myobj = MyObject("Mooo!")
print(type(myobj))

# Send to Java by casting wrapping it in a Proxy and then casting it to Java.
# Note you can use any interface you want here.  It doesn't check that 
# methods are implemented but you will get MethodNotFoundException if
# something tries to call a method on it.  (note the cast is not necessary
# here as proxies can be passed straight to Java)
jobj = JObject(JProxy("java.io.Serializable", inst=myobj))
print(type(jobj))

# and come back again by putting into Java and getting it back
ja = JArray(JObject)([jobj])
back = ja[0]
print(type(back))
print(back.data)
```

This is somewhat of an advantage over allowing JPype to convert as JPype would have tried to make it an ``org.jpype.PyObject`` under what I am implementing rather than letting you select a type.

Is this close enough to your use case to be worth applying?

**Comment by apatrida** [comment]
This is definitely going to work for me, would you apply it to a quick release, or a specific branch I can build from?

(thanks a ton, this is a great help!)

**Comment by apatrida** [comment]
> (note the cast is not necessary here as proxies can be passed straight to Java)

THis si the `JObject(...)` outer cast around the `JProxy` that is optional?

**Comment by Thrameos** [comment]
This one will need a little bit of thought before it can be applied.  The patch I gave strips off the Proxy view that lives as the outside of the Python object.  But that view of the object appears a lot of places including as the object returned as self when calling an interface.

So now that it is clear that what you are trying to achieve the next step is how to give you the functionality without busting something that someone may be using.  

Lets start with a quick leason on what is going on under the hood.  Proxies are the name that original author gave the Java invocation handlers.  By creating a proxy you are creating a new java object that serves as a view of one object that is pretending to be another.  But the original design had a very serious design flaw.  It creates an unresolvable reference counting loop.  The java object references the python and the python references java and neither can traverse the other because both references are outside the others system.  

So to resolve the design flaw I morphed tje meaning of proxies to become a factory that produces a an invocation handler on request.  When you use a proxy it creates a fresh invocation handler that points to python, but that invocation handler has no reference in python itself.  Cycle is solved.  But now we have all these useless invocation handlers that land back in Python.  Hence that piece of logic we are playing with.

Now the problem with the easy implementation is people can attach anything they want to the factory object and it will in fact transfer back from java to python.  If we strip the view we will be limiting that to just the instance from the proxy that was used to create it.  

Therefore I need to come up with a formulation in which the proxy view object still allows arbitrary stuff and gets you your object without a huge burden. 

The options are. 
1) apply the patch... loses funtionality...@marscher would likely object.
2) allow access to the proxy instance field... simple change but now you have to call a magic function to get the object back... bad as encourages users to poke private symbols.
3) create a new way of creating the proxy with new rules.  Doable... just need a behavior flag to control it.  But that is another API to maintain thus lots of thought.
4) hack the getattr so that the proxy pretends to be the instance when accessing the proxy.  This is the most flexible as it both gives you access to the fields and doesnt break existing code.  But it also creates the edge case that a view us not quite the same as the original and there will always be ways to tell. Requires 3 magic functions hidden in the private module.
5) check for ``__javaproxy__`` attribute on an object like py4j Java class designator.  Slows down everything because adds one attribute lookup to every object lookup.  Also means that you can only have one view for any object type... to big of performance hit, and less flexible.

Okay i need to sleep on this one some more... or maybe get more sleep...

**Comment by apatrida** [comment]
Here are a few constraints on how I would use my end that help for my case, but not necessarily a general one.

* Some API's in Python return objects that I must use in later calls to Python.

* I am usually wrapping the call to the Python objects and the returns because I am making the API jpype or py4j friendly.

* Therefore I have an opportunity to wrap/unwrap these objects going in both directions.  And I don't mind doing that explicitly.

But, what I cannot fix nor workaround easily is:

* Pass something back to Java that looks like a Python object that I can hold in a typed opaque class, i.e. my `PythonReference<Stlye>` to use in other calls requiring a `PythongReference<Style>`.  I do not need to call any methods on this object, I just need to hold it and give it back.

* Unwrap this without remote calls to get the members that pass the boundary from python->java->python, or at least in Py4j it proxies the members so to get my UUID back, it calls Java which then calls Python.

So a smaller solution would be a reference wrapper on both sides that the system just recognizes as something you want to hold but not interact within Java, and efficiently can return that to an object on the Python side.

This is like marking with an interface but in cases where you cannot do that (i.e. other library code that I cannot change).  It has all the wrap/unwrap calls but that is a better price to pay than crossing the JNI boundary just to pick up the UUID again.

Another option is to allow a primitive member of a Python class to be copied instead of proxied by some decorator/annotation.  To avoid reaching across the wire for a fresh copy (i.e. it is immutable and not changing and we want it passed by value, not by remote reference)

So if I was knowing much about the code, this would be the first pass I would try to do:

* Create a Python reference wrapper `PyReference[T]` (generic) that you wrap around references that you return to Java and get back unharmed.

* Create a Java matching class `PythonReference<T>` (generic) that holds these o the Java side and allows nothing to be done with them other than hold them.  Basically, it carries the UUID type long or string and nothing else.  It could print it for debugging purposes but otherwise is a "reference"

* When a reference is returned to `PyReference[T]` type on the Pythong side either automatically unwrap and restore the original object, or manually require a call to unwrap.

This basically takes what you have for "implements interface" and makes it manually usable for any object and not just those you have 100% control over.  Later you can make it completely automatic.  Here one direction could be.  I'd be happy with it being manual if only I can do the light-weight reference across the wire.

**Comment by Thrameos** [comment]
I am going to make this my weekend project along with dealing with ``wait``, ``toString`` and ``equals`` all of which are rather busted on the current API.   Wait is the hardest as we need to have an actual persistent object in Java to serve as the sync point.   I may punt on that one and just have it raise not supported.  There is also the minor problem of default methods which didn't exist when this API was created.  That is likely to touch the most code.  Last we can cut down the weight of this API a lot if we switch to a weak reference so that I can reuse the InvocationHandler multiple times.

So some ideas that are easy to implement....

1) Adding a ``JProxy.unwrap(obj)`` method which gives you back the instance object after it has be wrapped in a proxy.   This would allow you to easily transport something to Java and then explicitly get it back regardless of how the wrapper was created.
2) Adding a ``JProxy(interfaces, inst=obj, convert=True)`` which in the spirit of string conversions would automatically hand you back the object rather than the proxy view when dealing with the object. 

I think between these two we would cover all your needs (explicit and implicit conversion support).

That just leaves the question of whether ``JProxy`` should be checked.  Currently only ``JImplements`` actually does the right thing and tests for each method being implemented on Python side.  I have wanted to extend it to ``JProxy`` but it would break code.   So if I am going the kwargs route I would just make it ``JProxy(interfaces, inst=obj, check=True)`` so that the user controls if the interface is actually checked against the list of valid overloads.  That would be the most flexible though like the old convertStrings it leave the worst option as the default.

Any thoughts are always appreciated, though often one direction is much easier than another when it comes to implementation.

**Comment by Thrameos** [comment]
The ``JObject`` cast was just there to force it to be a Java object while still sitting on the python side.  You can make a proxy and pass it to any Java method, field, or array and it automatically casts itself to appropriate interface.   The only place an explicit cast is required when working with a proxy is when the Proxy implements multiple mutually exclusive interfaces.  Then you have to use a cast to pick one when sending it off.  (Yes you can implement many interfaces with one Proxy)

**Comment by apatrida** [comment]
> I think between these two we would cover all your needs (explicit and implicit conversion support).

yes, that combination definitely allows a lot of patterns to work, including mine!

> That just leaves the question of whether JProxy should be checked. 

By checking you meant that the Python object implements all methods of the Java interface?  That makes sense to do.  But, I don't like any extra Python methods being impacted beyond the interface, and I'm guessing you are not talking about that, it wouldn't make sense in most cases anyway.

**Comment by apatrida** [comment]
about 

> There is also the minor problem of default methods which didn't exist when this API was created. 

This might be an area I could help, from the Java side viewpoint.  I think a move to Kotlin and its reflection would be helpful here, because then you can cover the Java cases, plus defaulted parameters, plus nullability, and other special cases that are introduced above and beyond base Java.  Also, I can check the reflection code for caching and seeing what could be done to optimize the calls going into the java direction

**Comment by apatrida** [comment]
(also Kotlin can do keyword args for anything that is declared with a default value)

**Comment by Thrameos** [comment]
If you don't mind contributing tests to the test bench for Kotlin specific details I can certainly help support it.  I can augmenting as much as I can from reflection, but if you would like methods to actually do stuff beyond what Java does I would need some help.   If the annotations require tagging of method, fields, etc, then we can using reflecting in java to push those through just like we do with isBeanAccessor, isBeansMutator.   We can also install custom document hooks for Kotlin classes and methods so you can properly output language relevant details.

We had someone who wanted support for scala but they couldn't put in the time to build a test bench.  I would say the minimum is get the CI to use the package system to pull the required stuff for testing, a basic test script hitting all the language features, and the equivalent of a quick start guide showing how to translate the language into basic features so that if I had to debug something I would be able to do so.   (Fun fact.... I know almost nothing about Python beyond the stuff in the stuff in the C layer.  I am sort of like the mechanic who doesn't actually know how to drive.)

As for JProxy runtime checking.  The only requirement currently for checking is that every method in the interface must have a callable in the Python Proxy object.  That is if Java says you will have a callFoobar method, then the Python version that proxies it will be checked for a name match (with some substitutions for conflicting keywords).   We do not currently have enough support to check the number of arguments or types or anything as the strongly typed to weakly typed mapping makes that a real challenge.   There is a mapping such that all methods with the same name in Java match to one Python method (which has to serve as a dispatch).   I have some plans to make a stronger typed system using ``@JOverload`` in which if the Overload lists a bunch of arguments then it will automatically rename the Python method to a private member with a mangled name and create a dispatch method for Python to use.   But that is scheduled for work when I get the ability to implement Java classes from within Python which will required that detail.

I hope that clears things up on that front.

**Comment by apatrida** [comment]
Yeah, Reflection and Java/Kotlin is part of my history for sure, I've worked in the space in open-source over a variety of projects.  

Your `@JOverload` decorator is similar to Kotlin's `@JvmOverloads` which generates all permutations of the default parameters being used or not to benefit callers from Java.

A difference between Kotlin and Scala is that Kotlin interoperates 100% both ways with Java easily.  There is a perfect matching concept on each side.  Java just doesn't take advantage of some of what Kotlin can do on top, and sometimes you have to tell the Kotlin side to make the Java view easier (i.e. the `JvmOverloads` annotation).

Kotlin reflection 100% encompasses Java reflection and view of the world, with a simpler API, and then handles Kotlin issues on top of that.  You can code the Kotlin version to handle Java because Java just appears like a Kotlin class that is doing less cool things, it is the subset.

So taking your Java reflection, moving it to Kotlin and adding tests for both covers both at one time.  Plus as Java adds features that slowly catch it up towards Kotlin, the Kotlin reflection and runtime is always kept up to map to it correctly.

Maybe I'll glance at the code on the JVM side and see what it feels like.

**Comment by Thrameos** [comment]
The pull request for the required changes has been submitted for review.
