### ISSUE TITLE
[Question]: Do I have to manually manage the GIL when calling Java code from Python using JPype?

### ISSUE THREAD

**Issue by dclong** [jpype-project/jpype#638]
If I have a multithreaded Python program and in one thread I'd like to call Java code using JPype. In order to fully take advantage of multithreading, do I have to manually manage the Python GIL or does JPype manage it automatically?

**Comment by Thrameos** [comment]
The GIL is unlocked ever time that control passes from Python to Java.  It recovers the GIL when calling back from Java to Python.  It also automatically attaches Python threads to Java.   If you are using very heavy dynamic threads (as opposed to a small number of static threads) then you must remember to detach threads so that the Java memory is freed properly.

**Comment by Thrameos** [comment]
Please look over test/jpypetest/test_proxy_multithreaded.py for examples of working with threads.

**Comment by dclong** [comment]
@Thrameos Thank you so much for the explanation and information! This helps a lot!
