### ISSUE TITLE
Invocation of a JVM class ctor works only after several attempts

### ISSUE THREAD

**Issue by KOLANICH** [jpype-project/jpype#645]
Here are some keywords for search: `_hints can't be set`

Here is the reproducer https://gist.github.com/KOLANICH/583271f7411a35e7740939335bdb4b6a

Also I encounter a similar issue with classes - some of the classes are only imported after a second try.

**Comment by Thrameos** [comment]
Did #644 fix the issue?

**Comment by KOLANICH** [comment]
Works like a charm. Thank you.

**Comment by Thrameos** [comment]
Thanks for the bug report.  Some one beat you to it by about a day.  

This bug was one of those weird edge cases where the inner classes implements the outer class so we get a horrible race condition.  If we find the inner class first we load the outer class so the we have the context for the inner, but the postload on outer tries to load the inner classes.  In the end it created 2 copies and leaked the first, but the second one can't install itself because the first has already burned the one time use ``_hints`` slot.  The old system had the same race condition which created two JClass wrappers.  One lived on the inner class and the other ends up exposed.   It didn't trigger bad behavior but it it was detectable with the ``is`` operator returning false under probing the class relationships.

I think the short circuit I placed fixes it but I need to hit it with some test cases to make sure that all possible race conditions are working.  Once all the code is checked this will be included.
