### ISSUE TITLE
JImplements requires JVM to be running

### ISSUE THREAD

**Issue by pelson** [jpype-project/jpype#653]
The JImplements interface is really nice - it gives overrides checking and automatic proxying for a much more pleasant interface when dealing with nested objects than the equivalent ``JProxy`` approach.

Unfortunately the ``jpype.JImplements`` currently requires the JVM to be running which can be awkward to guarantee at module definition time. I'd rather not nest my class definitions to allow me to guarantee that the JVM has been started, instead I'd like to defer the work that is done in ``JImplements`` until I try to construct an instance of my class.

I hacked together an approach using the existing public API tools to do precisely this:

```
import jpype as jp


def JImplementsDeferred(*jimplements_args, **jimplements_kwargs):
    def JProxyCreator(cls):
        # Store the __new__ method, we are going to override it for the first
        # construction of one of these cls instances. After that, we can use
        # the original class's __new__ method.
        cls.__unwrapped_new__ = cls.__new__

        def __fast_new__(cls, *args, **kwargs):
            self = cls.__unwrapped_new__(cls)
            self.__init__(*args, **kwargs)
            return self

        def __new__(cls, *args, **kwargs):
            # JImplements modifies the class's __init__ in-place.
            if getattr(cls, '__jimplements_called__', None) is None:
                jp.JImplements(*jimplements_args, **jimplements_kwargs)(cls)
                cls.__jimplements_called__ = True
            # Now put the old __new__ constructor back on this class (as
            # this doesn't need to be called again).
            cls.__new__ = cls.__fast_new__
            return cls.__new__(cls, *args, **kwargs)

        cls.__fast_new__ = __fast_new__
        cls.__new__ = __new__
        return cls
    return JProxyCreator
```

I can then use ``JImplementsDeferred`` in exactly the same way as ``jpype.JImplements`` (i.e. as a class decorator).

It basically hijacks the object constructor to do the ``jp.JImplements`` magic (which is mostly override checking and attaching a ``__javaproxy__`` attribute). After doing this once it then reverts back to using the originally defined object constructor, so there is no subsequent performance penalty. I was tempted to re-implement the ``__javaproxy__`` logic from the JImplements wrapper, but actually calling the JImplements decorator itself turned out to be fairly clean and is making use of the public JPype API.

Are there any obvious flaws to this approach? Is this something you'd like to see in jpype?

**Comment by Thrameos** [comment]
Seems quite reasonable to me.  The reason for the current implementation is that we of course can't check the interfaces until the JVM is start and I don't want throw errors at random places thus I made it check at declaration time.   It is a bit unclear to me at what point does it actually do the checking of the Overrides.  I am guessing that it is at the first construction.  If so a small documentation block would make it more clear on the behavior.  

There may be a better way to construct this so that you don't actually need to swap the new methods around.   I would have to consider the pattern a bit more so that I can give a recommendation.  

The current implementation is of course createJProxy  
```
def _createJProxy(cls, *intf, **kwargs):
    """ (internal) Create a proxy from a python class with
    @JOverride notation on methods.
    """
#####
#  This get run once, but could move to a class hook called on first new call
    # Convert the interfaces list 
    actualIntf = _convertInterfaces(intf)

    # Find all class defined overrides
    overrides = {}
    for k, v in cls.__dict__.items():
        try:
            attr = object.__getattribute__(v, "__joverride__")
            overrides[k] = (v, attr)
        except AttributeError:
            pass

    # Verify all methods are overriden
    for interface in actualIntf:
        for method in interface.class_.getMethods():
            if method.getModifiers() & 1024 == 0:
                continue
            if not str(method.getName()) in overrides:
                raise NotImplementedError("Interface '%s' requires method '%s' to be implemented." % (
                    interface.class_.getName(), method.getName()))

    members = {}
####
#  This is just transferring the stuff from the precalculation stage to the user defined init
#  It is formulated like this to support both new and old style proxies, but there really 
#  isn't a need for them to use the same so I could split the new if needed to make this
# easeir
    def new(tp, *args, **kwargs):
        self = _jpype._JProxy.__new__(tp, None, actualIntf)
        cls.__init__(self, *args, **kwargs)
        return self
    members['__new__'] = new

## This is the sort of awkward part as we are going to end up making all proxies live in the 
# _jpype space rather than were they were constructed.  We set the __mro__ so that the
# new class is both the requested class and the _JProxy type
    # Return the augmented class
    return type("proxy.%s" % cls.__name__, (cls, _jpype._JProxy), members)
```

It does all the interface checking and then creates a type derived form ``_JProxy``.  The key advantage of this formulation is that the interfaces get checked once when the class is created.   The deferred version would obviously need to wait until the Proxy was constructed.  The alternative formulation would be to simply hold the arguments in the class declaration and pass them through to the new.  During new we could then check to see it the type has been configured and if not it would then automatically finish the class construction sequence.  Hmmm.... still needs a bit more thought.   I may be able to make it so that the pattern works with a simple keyword arguments like ``deferred=True`` but I would need to run some tests.   If I can make both formulations work through same interface that would likely be preferable.

If you would like to submit this as a PR add it to the ``_jproxy``.   You will need to use subrun pattern to make the test case of it so that you can test that it works properly before and after starting the JVM.   I can help you out if you need information on running that code.  Once I have the tests I can consider if there is a better way to achieve the same behavior.

**Comment by pelson** [comment]
Great. Thanks for the rapid response. I hadn't spotted your improvements a few days ago (#634). I think adding a deferred keyword argument makes some sense and believe it can be implemented with no extra cost in terms of storage/attributes on the generated class.

**Comment by Thrameos** [comment]
Okay I slept on this one and as expected I managed to come up with a fairly clean solution to the request.  I had to push a bit of the logic around but it should now be possible to create a Proxy using JImplements before the JVM is started.  Turns out to be pretty simple to defer the action until later as it took all of 15 minutes to implement.

This needs a few minor issues resolved before it is included.  (Missing tests and docs update)  But it should be testable.  Please look it over and see if it meets your needs.
