### ISSUE TITLE
Import problem, works with JPackage

### ISSUE THREAD

**Issue by petrushy** [jpype-project/jpype#700]
I had some examples that I've tried with jpype but I don't get the import to work. I have a test jar with some classes that I try to import.

in short

Cat = JPackage('org.jcc.test').Cat works
but 
from org.jcc.test import Cat does not work. from the doc and other tests I think it should work.

I have included a small test case in the attached zip. Not urgent but maybe good for troubleshooting.
[java-example-test-parameters-jpype.zip](https://github.com/jpype-project/jpype/files/4524608/java-example-test-parameters-jpype.zip)

**Comment by Thrameos** [comment]
The two most common reasons for imports to fail....   

First, if there is a directory named "org" in the Python search path then it will be called rather than Java imported class.   Python always searches for modules first so anything it considers to be 
 a module (directory or python file) will hide the Java imports.

Second if a class is not public it cannot be imported except by using a direct name request.  Currently JClass and JPackage can import protected and package protect classes.   With the JPackage improvement patch, only JClass can directly import protected and private resources. 

Looking at your example I believe the first applies.   (My coworker did the same thing last night when he created a directory named java and hilarity ensued.)

**Comment by petrushy** [comment]
Ah, thank you, yes it is the org folder that messes things up! 

Yes, sounds like a good principle that the standard import do not import protected classes.

Keep up the great work.
