### ISSUE TITLE
automatic conversion of python lists in parameters does not work until java.util.Collection(?) is imported

### ISSUE THREAD

**Issue by michi42** [jpype-project/jpype#721]
Assume the following Java class:
```java
package jptest;
import java.util.Collection;

public class Test {
    public static void testMethod(Collection<String> input) {
        System.out.println(input);
    }
}
```
invoked by the following python code:
```python
import jpype

jpype.startJVM(
    jpype.getDefaultJVMPath(),
    classpath='/path/to/built/class,
    convertStrings=True
)

import jpype.imports
jpype.imports.registerDomain("jptest")

# from java.util import Collection

from jptest import Test

Test.testMethod(["a", "b"])
```

Expected result:
```
[a, b]
```

Actual result:
```
Traceback (most recent call last):
  File "D:/jpype-playground/test.py", line 16, in <module>
    Test.testMethod(["a", "b"])
TypeError: No matching overloads found for jptest.Test.testMethod(list), options are:
	public static void jptest.Test.testMethod(java.util.Collection)
```

Once `java.util.Collection`, `java.util.ArrayList` (or probably any other collection?) is imported, e.g. in the commented-out line, conversion works as expected.

JPype 0.7.3, Java 1.8 (x64) on Windows 10.

**Comment by Thrameos** [comment]
Interesting feature.   Yes it appears that the converters are getting dynamically loaded (not intentionally).

The converters are loaded when the class is first encountered in JPype.   But in this case as the method is using a type that has not yet been encountered.   Method call is not being counted as a usage.  This is primarily a defensive call, as pulling in every class that used in a method causes a type explosion at startup.   

The fix is to have method dispatch refresh all types prior to starting the method resolution process.  It isn't a terribly difficult fix, but it will take some testing to make sure there are no side effects from adding a check to the resolution at that point.

**Comment by Thrameos** [comment]
The "fix" is in ``jp_class.cpp``

```
JPMatch::Type JPClass::findJavaConversion(JPMatch &match)
{
	JP_TRACE_IN("JPClass::getJavaConversion");
	// Update the Python class cache
	if (this->m_Hints.isNull()) // check if the hints are missing (meaning this class was never loaded)
		PyJPClass_create(*match.frame, this); // update the Python type cache
	if (nullConversion->matches(match, this)
			|| objectConversion->matches(match, this)
			|| proxyConversion->matches(match, this)
			|| hintsConversion->matches(match, this))
		return match.type;
	JP_TRACE("No match");
	return match.type = JPMatch::_none;
	JP_TRACE_OUT;
}
```
