### ISSUE TITLE
Changing classpath in runtime doesn't work.

### ISSUE THREAD

**Issue by KOLANICH** [jpype-project/jpype#771]
So I currently have to use the perversions https://github.com/KOLANICH/JAbs.py/blob/master/JAbs/impls/JPype.py#L51L105 as a workaround. instead of a simple https://github.com/KOLANICH/JAbs.py/blob/master/JAbs/JVMInitializer.py#L90 .

But it has an issue: packages added into classpaths at different times cannot interact. I mean I add one package (antlr), then it generates code, then I import the package that compiles the code (using mdkt compiler), compile the code and load it in runtime (these steps are done within mdkt compiler). But the code compiled uses antlr itself. So, I get an error. I can workaround it by loading them into the same `URLClassLoader`, but it has an issue - I won't be able to split a wrapper for mdkt compiler and a wrapper for antlr into separate libs.

**Comment by Thrameos** [comment]
This requires some tweaking to work.  Libraries loaded with different class loaders are not allowed to interact in Java other than through parent child relationships.   You would need to create a custom DynamicClassLoader class which could have new classpaths added at runtime to work.   It would still not work in some cases as classes that are loaded using the System classloader still can't see the dynamic ones.  (Same with the JPype bootloader.)    The default URLClassLoader doesn't support this sort of thing.

When I do this with dynamic loaded classes I build a fully custom classloader which knows how to call asm to build classes and then load them.  

I suppose you could get this to work if you chained then where each URLClassLoader as the previous as the base.   But a full custom one that has a pool of URLClassLoader that it calls getResource() would likely be safer as you would be able to add at any time in any order.

**Comment by KOLANICH** [comment]
I wonder if it is possible to make classpath modification after the VM has been started work, so I won't have to use custom loaders, just have to just add the needed jars into classpath and just import as if it was in flasspath at VM start, as I do in GraalPython?

**Comment by Thrameos** [comment]
I read pretty deep into the ClassLoader structure especially since I wanted the reverse bridge to be able to unload a dynamically created class.   The underlying class loader for Java is very inflexible.   People end up playing a lot of tricks to try to get classloaders to behave more reasonably.   The standard class loader takes the path when it is created and caches it so there is no way to modify the path.   It also caches all classes created in an inaccessible list so that you can't reload a class with a new definition which makes what I am trying to do with the Java to Python bridge hard.   Looking through it made me feel like I was taking a journey back before the JVM was used for any other language than Java as it certainly would make some very reasonable things very hard to do.

The best solution I have seen is to make a separate classloader for each Jar with a base loader the knows how to delegate back to the correct loader.  That way that each of the jars are in their own loader so that they can be dumped if you want to replace them and have them load together as one.   I debated making such a system for JPype but decided that it would be best to push it to the next major release as although it is very useful to be able to dynamically load classes in Java, I can't justify it until I have a working reverse bridge.  Again this is a lot of custom code.   

That still does not guarantee that the JVM will actually dump a class when all instances are dead.  

I also have plans for a Python Java module extension builder which builds the Jar piece of the module so that someone can more easily ship the Jar and Python module together as one and load the Jar from the Python module ``__file__`` path.  That would make it much easier to ship the required custom code rather than having to build and install it separately.   But these are all 6-9 months in the future.

**Comment by KOLANICH** [comment]
Thank you for the extended answer.

**Comment by Thrameos** [comment]
I believe this is the code that you require for the task pulling from my experiment snippet stock. This wasn't tested to production code levels; you have been warned.

With this you can add the fixed jars after the JVM is started, create a new set of dynamic classes, and add them to the dynamic classloader and have them all act like they are in the same classloader.  It uses the slaved URLClassLoader trick, but it currently does not support unloading or other fancy tricks as that requires an additional support classes.  

```
package org.jpype.classloader;

import java.io.ByteArrayOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.net.URLConnection;
import java.nio.file.FileSystems;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.LinkedList;
import java.util.List;

public class DynamicClassLoader extends ClassLoader
{

  List<ClassLoader> loaders = new LinkedList<>();

  public void addFiles(Path root, String glob) throws IOException
  {
    final PathMatcher pathMatcher = FileSystems.getDefault().getPathMatcher(
            glob);

    List<URL> urls = new LinkedList<>();
    Files.walkFileTree(root, new SimpleFileVisitor<Path>()
    {

      @Override
      public FileVisitResult visitFile(Path path,
              BasicFileAttributes attrs) throws IOException
      {
        if (pathMatcher.matches(path))
        {
          urls.add(path.toUri().toURL());
        }
        return FileVisitResult.CONTINUE;
      }

      @Override
      public FileVisitResult visitFileFailed(Path file, IOException exc)
              throws IOException
      {
        return FileVisitResult.CONTINUE;
      }
    });

    loaders.add(new URLClassLoader(urls.toArray(URL[]::new)));
  }

  public void addFile(Path path) throws FileNotFoundException
  {
    try
    {
      if (!Files.exists(path))
        throw new FileNotFoundException(path.toString());
      URL[] urls = new URL[]
      {
        path.toUri().toURL()
      };
      loaders.add(new URLClassLoader(urls));
    } catch (MalformedURLException ex)
    {
      // This should never happen
      throw new RuntimeException(ex);
    }
  }

  /**
   * Loads a class from the class loader.
   *
   * @param name is the name of the class with java class notation (using dots).
   * @return the class
   * @throws ClassNotFoundException was not found by the class loader.
   * @throws ClassFormatError if the class byte code was invalid.
   */
  @Override
  public Class findClass(String name) throws ClassNotFoundException, ClassFormatError
  {
    String aname = name.replace('.', '/') + ".class";
    URL url = this.getResource(aname);
    if (url == null)
      throw new ClassNotFoundException(name);

    try
    {
      URLConnection connection = url.openConnection();
      try (InputStream is = connection.getInputStream())
      {
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        int bytes;
        byte[] d = new byte[1024];
        while ((bytes = is.read(d, 0, d.length)) != -1)
        {
          buffer.write(d, 0, bytes);
        }

        buffer.flush();
        byte[] data = buffer.toByteArray();
        return defineClass(name, data, 0, data.length);
      }
    } catch (IOException ex)
    {
    }
    throw new ClassNotFoundException(name);
  }

  @Override
  public URL getResource(String name)
  {
    for (ClassLoader cl : this.loaders)
    {
      URL url = cl.getResource(name);
      if (url == null)
        continue;
      return url;
    }
    return null;
  }
}
```

**Comment by KOLANICH** [comment]
Thanks.

**Comment by Thrameos** [comment]
Did this code work for you?  I switched the bootloader for JPype to the Dynamic loader for development branch so we should be able to support just calling ``addClassPath`` statements to add new jars to the path after the JVM is started.

**Comment by KOLANICH** [comment]
I'm sorry, I'm currently a bit busy, so I haven't found the time to redesign and test the part of JAbs loading packages. Could you, please, point to the branch I should try and the code changes allowing to add packages in runtime (I have looked at `_classpath.py` in all `master`, `devel` and in your personal repo and haven't found there anything actually loading packages in runtime)?

**Comment by Thrameos** [comment]
It is currently in epypj repo which is for the next cycle of development.  I can push it out devel repo once I have completed the current release.

**Comment by KOLANICH** [comment]
I have tried the trick you have described with chaining of loaders. It seems it doesn't work. I still get NoClassDefFoundError.
