### ISSUE TITLE
Directories with .class files not recognized as classpath entries

### ISSUE THREAD

**Issue by kasparthommen** [jpype-project/jpype#775]
Hello,

It looks like jpype can only handle .jar files as classpath entries, but not directories containing package folders and .class files, even though the documentation mentions the standard "classes" directory as possible classpath entry, see here:

https://jpype.readthedocs.io/en/latest/userguide.html#controlling-the-jvm

```python
import jpype
jpype.startJVM("-ea", classpath=['lib/*', 'classes'], convertStrings=False)
```

Would be great if that worked because that would decrease the turnaround time by not having to build .jar files but access the compiled .class files directly.

**Comment by Thrameos** [comment]
I can assure you that JPype does pick up directories assuming they contain proper package names. The behavior of what is accepted is a function of the JVM and not JPype.

For example during testing the files under ``test/harness`` are compiled to ``test/classes`` which is then included using ``jpype.startJVM(classpath='test/classes')``.  Further in development, the internal jar is included using ``jpype.startJVM(classpath='project/jpype_java/build/classes')`` so that it does not have to be recompiled into the thunk.

The most likely issue is that your class files don't have the correct structure.   For example, if your classes are ``org/foo/Test`` then the classes directory would need to be ``classes/org/foo/Test.class``.  The second most likely is that when accessing classes with non-TLD class names usually ``JClass`` needs to be used.   As far as I am aware JPype can't pick up non-packaged classes other than directly calling them with JClass.  Last, you may have forgot to make your classes public which means that they can't be loaded.  There are other potential errors such as missing dependencies and such that will also cause the classpath to fail to load, but those issue warnings that should direct you to a resolution.

Example:  Test.java
```
public class Test {
    public static void main() {
        System.out.println("hello world");
    }
}
```

compiled with ``javac Test.java`` produces ``Test.class`` in the directory.

Runs with
```
import jpype
jpype.startJVM(classpath='.')
Test = jpype.JClass('Test')
Test.main()
```

To produce ``hello world`` as the output.  So even unpackage classes can be loaded and used.  I use this feature all the time where I need a small piece of Java code during development.

**Comment by kasparthommen** [comment]
@Thrameos Thanks, I have indeed failed to set things up correctly - using class directories works now! :-)
