### ISSUE TITLE
^C on non interactive sessions

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#778]
We added a signal handler so that we don't crash out of interactive sessions in Python from the Java handler, but when running a non-interactive session that may be the proper behavior.  Often when running a big script a ^C means stop the process and thus letting Java ignore it so that we can fall back to an interactive shell doesn't make sense.   Should we add an option to startJVM() which enables or disables signal behavior.   If not set it would autodetect based on isatty() and ``sys.ps1``.   

Something like 
- jpype.startJVM( interrupt=True) - ^C stops process
- jpype.startJVM( interrupt=False) - ^C breaks Java if possible and returns control to Python
- jpype.startJVM() - ^C selected interrupt if not interactive shell.

Does this make sense?

**Comment by ShaheedHaque** [comment]
For my use case, JPype is running in a child of a server process (i.e. Celery) which has a "stop" CLI command. When I need to stop the thing, I initially invoke the "stop" CLI command. If that does not work, I will resort to using kill with increasing levels of abruptness to force the issue.

- I don't know how "stop" is implemented between the parent server and its worker child processes.
- I'd prefer not to be tied to a particular set of abruptness levels since I have had to change things from time to time (though, for now, I use SIGINT, SIGTERM and SIGKILL).

I think your description above means the latter would continue to work with the default invocation, right? I guess neither of us can be sure about the former without further work.

**Comment by Thrameos** [comment]
Currently the SIGINT is being routed back to Python with Java interrupt sent to all nondaemon threads.    Unfortunately, Java interrupt is only respected if something is waiting on IO.   If it is not then Java would proceed until the next IO point.   This is an issue because a pure computation command will never respect the interrupt.  But as the call is routed to Python we ensure that the shutdown point is now defined and thus order is ensured.

In contrast, the default for Java without this would be for JVM to start shutdown which as far as I can tell cannot be aborted.   If we want to have support for ^C in an interactive shell I have to disable the shutdown.   

I don't think there is much change either way for you.   Your application is likely heavy on the IO end so the interrupt will likely caught and transferred to Python where an orderly shutdown can proceed.  If not then "interrupt=True" would be the option as it will ensure the process stops.  Though the orderly part is somewhat doubtful in that case.   Python likely was not ready for the JVM to shutdown and thus will get fails on pending JVM calls and Proxies.  I think I have patched everything needed so that it won't segfault by holding the shutdown process until the last proxy exits as once the C++ resources disappear it all starts falling apart.   I suppose I could start adding reference counting to the resources to hold them alive a bit longer, but once the JVM passes the point where the JPypeReferenceQueue has died then calls start segfaulting regardless.

**Comment by ShaheedHaque** [comment]
Thanks for the thoughtful analysis. My application will indeed be doing some I/O, and the actual core computation is unlikely to take an extended period of time for the forseeable future, so as you say, I should be ok...
