### ISSUE TITLE
JByte(in python) can't be recognized as byte(in java) when finding overload

### ISSUE THREAD

**Issue by zhc7** [jpype-project/jpype#783]
![image](https://user-images.githubusercontent.com/53651354/87226905-88409c80-c3c9-11ea-92b6-3984bfc6abe2.png)

**Comment by zhc7** [comment]
it turned out that it was i forgot to instantiate this class

**Comment by Thrameos** [comment]
Yeah.  The error message for static vs instance methods is unfortunately very difficult to recognize.  Currently the difference is one word "static" which did not appear in the error message telling you that it must be an instance method.  I should make it include the word "instance" or some such to make it more clear.  The way that the code gets to that point there is no way to know if it was called as a static or instance method, so we are relying on the user to recognize the method is not static in the error report and then realizing they called it statically in their code.  More than once I have fooled myself because I was trying to call a instance method as a static and spend 15 minutes casting only to realize I misread the message.   I will try to address this after 1.0 release.
