### ISSUE TITLE
Windows wheels for Python 3.7+ missing from JPype 1.0.1 release

### ISSUE THREAD

**Issue by John-Hennig** [jpype-project/jpype#798]
The "assets" of the [JPype 1.0.1 release](https://github.com/jpype-project/jpype/releases/tag/v1.0.1) do not, at this point, include "wheels" for Windows and Python 3.7 or 3.8. There is a Windows wheel for Python 3.6, but not for any Python version above that. The [previous JPype release](https://github.com/jpype-project/jpype/releases/tag/1.0.0) did include such builds.

Are you aware of this?

**Comment by Thrameos** [comment]
Must not have been uploaded properly.  I will fix when i am back in range to the internet.

**Comment by Thrameos** [comment]
@marscher For unknown reasons only a portion of the downloads that I pulled for the 1.0.1 release got uploaded.  It appears to have skipped manylinux_686 files and win-37, win-38 files.  Guessing the download on my web browser hadn't finished the downloads when I started the drop and drag to the release.  Can you push these to PyPI?  

I will have to cut a 1.0.2 to deal with some of the other issues over the weekend.   The 3.5m files appear to be corrupted due to a problem in the build system where it was using a late patch version which has an extra symbol.  A few other minor issues have also cropped up that warrant a repair.

**Comment by marscher** [comment]
I've uploaded the missing files. Sorry for the delay.
