### ISSUE TITLE
Using jpype for models in JARs - Dynamically adding/removing jars

### ISSUE THREAD

**Issue by AbdealiJK** [jpype-project/jpype#849]
Hi, I have a use case where I use models written in java quite frequently. and I'm trying to figure out how to import these java models and use them in my python application.

My application is as follows:
 - A user uploads a jar into my django application
 - I save the jar in some standard location
 - The user can now choose a model/jar that they have uploaded - and "run" it with certain inputs - and my application returns the model/jar's output back to the user.

The issue I'm facing is how can I dynamically add (and import) a jar without restarting my python application.

**So far:**
The way to run these models is to create a `.jar` file out of them, import the right class and call the `.score()` or `.predict()` function from there.
Currently, I'm doing something like this:
```python
jvm_initialized = False
def run_jar(inputs, jarfile):
    global jvm_initialized
    if not jvm_initialized:
        import jpype
        import jpype.imports
        jpype.startJVM(classpath=[jarfile])
        jvm_initialized = True
    from mymodels.model1 import Model1Evaluator
    return Model1Evaluator().predict([1,2,3])
```
But the problem is that once the JVM has started for the first model/jar ... the second model/jar fails to load, because it is not present in the classpath (and the JVM has already started)

**Potential Solutions**:
I thought about closing the JVM and starting a new JVM with a new classpath - but I see in the docs that once the JVM is shutdown, it cant be started again: https://jpype.readthedocs.io/en/latest/api.html#jpype.shutdownJVM

Is there any solution for such cases where JARs need to be dynamically loaded ?

**How the model/jar looks like**:
 - A java class which performs some logic and returns the model's output
 - Models in H2O's POJO format - http://docs.h2o.ai/h2o/latest-stable/h2o-docs/productionizing.html#what-is-a-pojo

The way it works is that I have a `.java` file which contains the scoring code required to run the model. For example:
 - If the model is a linear regression it has the logic of `a1*x1 + a2*x2 + ...`
 - If it is a gradient boosting model, it has the `if ... elif ... else` conditions to perform the splits

**Comment by Thrameos** [comment]
You can dynamically load classes in a JVM though the answer is a bit complicated.   To load a jar after the JVM is start you need to use a custom class loader.   For example, Java supplies a URLClassLoader which serves this purpose.  If you create a URLClassLoader pointed to the location of the jar files (or even bare class files) that you require and then use JClass with the classloader option keyword, it should dynamically load the jars.  If you create a second copy of the URLLoader and change the jar files, then JClass should be able to load the new jars.  The two instances will not be compatible of course so avoid loading them using the higher level api (JPackage, imports).

Now here are the complications:

Java does not support unloading of classes that have already been loaded as the Class loader holds a permeant reference to loaded classes.  In theory if your URLClassloader goes away then the classes will unload, though thus far there is no evidence that it works.   So although the class instances will get garbage collected the classes themselves may still live on.  

Second there is the issue of layering.   A class loader can only access classes that come from the classloader instance or from its parent.  Thus there are situations in which you load a class from a custom classloader and then attempt to call something from the system application and the security monitor will  fail to accept the loaded class because the dynamically loaded was not loaded with the same class loader.  The solution is of course to make sure that all of the classes belong to the same class loader instance.

The module level API does not recognize classes loaded manually and if you load more than one class with the same name it is hard to tell which instance you have.   It is best to keep all of the JClass instances in some kind of incapsulating python class so that it is workable.

Finally,  consider if it is better to use an interface rather that trying to dynamically insert dynamically generated Java code or other the other alternatives.   Python can implement java interfaces though this does have some overhead which may be a concern in your application.   Alternatively there are methods using Java ASM that can be used to create new Java lambdas at runtime.   This may give a better presentation if you simply create a factory for the user to create the evaluator they want and then either use Java or Java ASM to generate the method you need.  Typically this creates classes with the "$" naming notation thus avoiding the potential for naming conflicts.  Though this option does require some very specific knowledge of the Java virtual machine, but it is not that hard if the field names are available (and somewhat regular).   I have some examples of this in the epypj branch in which I used ASM to generate Java classes with callback hooks on the fly.  I did this by first producing some examples of simple classes in which I wanted to evaluate certain functions, then calling the javap command to dump the asm to a file.  I then copied that code to the asm library until each of the operations that I wanted to perform were able to be replicated as pattern.  I then created an API which allowed the user to specify the which operations were required and simply used the cookie cutter patterns to assemble into a class that I could then load from memory.  The result is new classes at runtime.  The regression model seems like just piles of access field, load constant, multiply, add stack operations.   Though I don't see a reason that a simple class with fields can't preform the same operation.
