### ISSUE TITLE
jpype picks up wrong (?) getDefaultJVMPath

### ISSUE THREAD

**Issue by nils-braun** [jpype-project/jpype#851]
Thanks for this great project!

For a test, I needed to install jpype on a windows server (windows 10) from conda-forge (1.0.2) additional to openjdk version 11.0.6.

When I call `startJVM()` without jvmpath argument, it fails due to an access violation exception. The problem is, that (for whatever reason), `jpype` thinks that the correct dll path is in $JAVA_HOME/bin/bin/server, instead of $JAVA_HOME/bin/server what I would expect.

```python
>>> import jpype 
>>> jpype.getDefaultJVMPath() 
'.... \\Library\\bin\\bin\\server\\jvm.dll' 
```
Side note: both in bin/bin/server as well as in bin/server exist a jvm.dll.

If I set the path by hand, it works as expected. My java knowledge is unfortunately not good enough to understand, why there is an additional jvm.dll in bin/bin/server or if this is already the problem (and `jpype` is just unlucky picking this one up).

**Comment by Thrameos** [comment]
The code in question is Python code in `jpype/_jvmfinder.py`.  As it works pretty much uniformally for other people I suspect that it is something specific to your installation.  Do you have JAVA_HOME pointed to the top level of the tree or the bin directory?  

As far as debugging I would say adding some print statements to the `_jvmfinder` to figure out which path in the code it took (registry, search, environment variable) would help you narrow down what went wrong.   Unfortunately as the test system only hits the one code path used on the test system, it is possible that you are hitting a bug in one of the less used paths.  (We usually have this happen on OSX because some of those have changed with the os version).

**Comment by nils-braun** [comment]
Very quick answer! Thank you very much. 

`JAVA_HOME` points correctly to the top level tree.

In my case, it uses the file-name based search. The "problem" is, that there also exists a jvm.dll under the path "bin\\bin\\server\\jvm.dll" - it just does not work with this jvm.dll. I think the only possibility to catch this is to try starting the JVM with the first jvm.dll candidate, then the next one etc. - but this does not sound quite efficient :-)

I guess - if you have never seen this problem - it seems to be an issue with the openjdk conda installation and I need to find out, why there actually exists an additional "jvm.dll" in the folder which does not work...
