### ISSUE TITLE
How to cast from python to java

### ISSUE THREAD

**Issue by enjoybeta** [jpype-project/jpype#875]
I have a java method with signature as shown below
`public Object foobar(int var1, Object[] var2) {...}`

I could successfully using Java code below to invoke this foobar method:
```
int var1 = 0
int[][] var2 = new int[1000][4];
foobar( var1, (Object[]) var2 );
```
I tried to invoke directly in Python with JPype as shown below, but returned with an error message `TypeError: No matching overloads found for edu.uw.bothell.css.dsl.MASS.Agents.callAll(JInt,list), options are: public java.lang.Object foobar(int,java.lang.Object[]) ......`
```
var1 = 0
var2 = [[0]*4]*1000
foobar( var1, var2 );
```

I also tried to cast var2 to an array of JObjects but returned with an error message: `TypeError: Unable to convert`
```
var1 = 0
matrix = [[0]*4]*1000
var2 = JArray(JObject)(matrix.tolist())
foobar( var1, var2 );
```

How can I invoke foobar(...) correctly? Or how can I cast the Python 2d list to Java Object array with JPype?

**Comment by Thrameos** [comment]
JPype can't guess the type to convert the array to, so you need to give a hint.   The type you are looking for in Python is a ``jpype.JInt[:,:]`` which is the same as Java ``int[][]``

```
# Create a Java array directly and use it with an explicit cast
var2 = jpype.JInt[1000,4]
test.foobar( var1, (jpype.JObject[:]) @ var2 )

# Without a cast works just fine too
var2 = jpype.JInt[1000,4]
test.foobar( var1, var2 )

# Casting to Java array from a list
matrix = [[0]*4]*1000
test.foobar( var1,  (jpype.JInt[:,:])@matrix)

# Casting to Java array from a numpy array (notice the dtype can be used to specify)
matrix = np.zeros((1000,4), dtype=np.int32)
test.foobar( var1,  (jpype.JInt[:,:])@matrix)
```

JPype supports many dimensional conversion thought not to something generic like Object[] or Object without first telling it how to cast.   After all the list could have wanted to go to ``double[][]`` or ``short[][]`` just as easily.

Please note that ``@`` is the casting operation.  The copy constructor form would also work.

**Comment by enjoybeta** [comment]
Thank you!!! You explained detailedly and that part of the code is working perfectly!

But I am having another similar scenario not quite working, its signature is shown below
`public Object foobar2(int[] var1, Object[] var2) {...}`

In java, I would invoke in this pattern
```
Integer[] var1 = new Integer[] {0, 1};
Integer[] var2 = new Integer[] {0, 1, 2};
foobar2( var1, var2 );
```
I tried to do a similar thing to foobar2 as your code shown
```
var1 = [0,1]
var2 = jpype.JInt[3]
var2[0] = [0]
var2[1] = [1]
var2[2] = [2]
var2_cast = (JObject[:]) @var2
print(var2_cast[0]) # output None
foobar2(var1, var2_cast)
```
But foobar2(...) exited with `java.lang.NullPointerException`, it seems var2 was not correctly cast to Object[] in my syntax
I didn't find any wiki/tutorial on how to do this with JPype, did I miss them somewhere?

**Comment by Thrameos** [comment]
The correct translation of the above code would be

```
import java
var1 = java.lang.Integer[:] ((0, 1))
var2 = java.lang.Integer[:] ((0, 1, 2})
foobar2( var1, var2 );
```

The key issue here is ``JInt`` is the Java type ``int`` but you were looking for the boxed type ``java.lang.Integer``.   Those are very different types in Java, so you have to pick the right one.   There is a "short cut" in that ``JObject(n, JInt)`` will box an integer for you.   But I rarely use it as specifying the Java type explicitly is much cleaner.  JPype does have some legacy constructs  from back when it was harder to get at the Java classes directly.

Array syntax is a bit weird, I know.  This is also a bit of a legacy item.

```
1) Python "Type[n]" => Java "new Type[n]"
2) Python "Type[:](n)" => Java "new Type[n]"
3) Python "Type[:]((a,b,c))" => Java "new Type[]{a,b,c}"
```

This is because the old style ``JArray`` used a single argument as the number of elements and a list of elements for initialization so the same logic applies to the unspecified length operator ``[:]``.

You can use the unspecified form to create a type object.

```
JI1 = jpype.JInt[:]
JI2 = jpype.JInt[:,:]
a = JI1(4) # equal to "new int[4]"
```

Most of this information should be found in the quickstart guide.  If you think that it isn't covered well just add some more examples to the quickstart.py, rebuild it, and send in a PR.

**Comment by enjoybeta** [comment]
The code working for me right now is:
```
var1 = JInt[:] (JInt(1), JInt(2))
var2 = java.lang.Integer[:]((JInt(0), JInt(1), JInt(2)))
foobar2(var1,
             (JObject[:]) @var2)
```
For the quickstart guide, do you mean the "quickguide.py"?

**Comment by Thrameos** [comment]
Hopefully dealt with in #889
