### ISSUE TITLE
JPype crashes when JIT compilation is enabled

### ISSUE THREAD

**Issue by karllessard** [jpype-project/jpype#885]
Hi,

I'm running into an issue where JPype crashes when JIT compilation is enabled, I am forced to use -Xint when starting the JVM to prevent the failure, which can happen in arbitrary places.

It is hard for me to tell which environment crashes first: the JVM or the Python process, see error message below. I've tried on different JREs (Oracle 1.8.0_151 & 1.8.0_172, OpenJDK 11.0.1) and the problem remains. I am on MacOSX 10.14.6 and uses Jpype 1.1.2 on Python 3.8.6.

I don't know if and why that could be the issue but the Java code I'm running is written originally in Kotlin. Is there anything I can try to reenable JIT compilation, since without it performances are extremely poor?

Thank you,
Karl

Error message:
```
Fatal Python error: Bus error
Thread 0x000070000261d000 (most recent call first):
<no Python frame>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (sharedRuntime.cpp:549), pid=9833, tid=0x0000000000000307
#  guarantee(cb != NULL && cb->is_nmethod()) failed: safepoint polling: pc must refer to an nmethod
#
Fatal Python error: Aborted
```

**Comment by Thrameos** [comment]
Hello fellow Karl.  This one is a little beyond my knowledge unfortunately.   There is nothing in JPype that should require the interpreter.   As far as I am aware we can run with full JNI checking which should catch any mishandling of the JNI calls.   The only exception to this is there is currently a call to request a virtual on an interface method which appears to mess up android based virtual machines.

**Comment by karllessard** [comment]
Hi @Thrameos , I can believe this is a tough one! I'm quite a new user to JPype though so I'm not sure to understand all particularities of this project yet, when you say : "we can run with full JNI checking", do you mean you want me to enable some sort of debugging session to see if the issue occurs in JPype JNI code?

I've just did the same test on Linux and I still have the same problem: my process crashes unless I enable `-Xint` in my JVM command. Also executing the same piece of Java code in a Java stand-alone app, without `-Xint`, works without problem. So it has to have something to do with the Python bridge somehow. Any traces you would like to see in particular?

**Comment by Thrameos** [comment]
JPype is just steering around the JVM using JNI calls.   Fundamentally it should be no different than Java calling natively.   The common problems that we can have is either we mess up a referencing count and call a resource which is not currently alive in terms of a reference, leak a reference by failing to close, or call a method using the wrong access pattern (attempt to use the wrong class for the method or force a non-virtual call on a method without an implementation.)  

The JVM has an option to try to catch as many of these as possible by forcing them to be be segfaults.  This prevents them from running silent.  The option is ``-Xcheck:jni``.  

Beyond that I can only point you to the two debugging chapters in user and development guide.  Those recommend "trace" and "gdb" based debugging.   If you can post some code as to which call you issued at the time of the fault (which method and it signature) I can see if it matches the pattern seen on the dex bug.  I can also give a patch fix for that so you can try it, but as it is a fairly complex problem it may be a week of so to get you a working patch.  

Last you can use javac to look at the byte code of the failed method.   If it really is a bug in the JVM it likely will be below the level where JPype interacts.   Though we can make mistakes in the JNI access, I am not aware of anything that would be fixed by turning off JIT.   I run with JIT all the time without issue.

**Comment by karllessard** [comment]
Ok I'll try first with the `-Xcheck:jni`, thanks

For the example code, I can send you something but the issue does not occur only in a single method, it especially happens inside loops of thousands of iterations. FWIW, adding some `System.out.println` inside the loop with JIT enabled seems to postpone a bit the problem (one loop can succeed, then a different loop in another method will fail), if that can help...

**Comment by Thrameos** [comment]
As this is a JIT issue, we need to consider the method after JIT runs.   That is it calls the method 100 times, then decides to compile it, then on the 101th time we called X.Y(Z) and it crashed with AAA.   

I would need to see the method signature of the call and its relationship to the objects.   For example we are calling method Y which was defined in object X as an abstract method which was implemented as Z.   The class structure is important here because method X.Y and Z.Y are two different memory addresses.   It is possible that JIT is changing the address of a method and somehow we have a stale method handle.  

Also important if there is some threading involved.  We can get old addresses if there is recursion and we unwind onto a stale address. 

Unfortunately, as I haven't seen anything like this it is going to be hard to track down with out a lot of information.

Just for clarity you are not perhaps using the non-virtual calling method deliberately.   For example....

1) a.method(b)
2) A.method(self, b) 

mean different things to JPype.   The first is getting the method for the type of "a" then calling a virtual method with argument b.  The second is looking up A.method and calling it non-virtually such that it always gets A.method even if C.method should hide A.method.   This can potentially foul things up if C.method does not actually call A.method.

**Comment by Thrameos** [comment]
I verified that the virtual bug is not happening on Oracle based JVMs.  It must be particular to dex so it can't be affecting you.

So I guess the next steps are on you.  Please post

1) the call in Python that is crashing
2) The method signature which is being called in Java
3) The class structure (abstract, inherited from etc) so that I can see how JNI likely called the method.

**Comment by karllessard** [comment]
Hi @Thrameos , 

I've narrowed down my code until I hit the breaking point and I've found out the issue. I'm running some machine-learning code with TensorFlow in my Python script and I was using [`tf.compat.v1.app.run`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/app/run) to start it, which happens to not be required anymore in my case.

So by simply replacing this:
```python
def main(args):
    # Call Java code here

tf.compat.v1.app.run()
```
by this:
```python
def main():
    # Call Java code here

if __name__ == '__main__':
    main()
```
JIT compiler can now run without any issue. I don't know why `tf.compat.v1.app.run()` is in conflict with JPype, I didn't try to find out neither, I'm just happy that now it runs smoothly. Unless you have more questions and want us to investigate further, I'm fine closing this issue. Thanks a lot for your help.

**Comment by karllessard** [comment]
Actually, the same problem occurs if I'm using [`app.run()`](https://abseil.io/docs/python/guides/app) from the `absl` package instead of `tf.compat.v1.app.run`.

**Comment by karllessard** [comment]
Ok... I couldn't refrain myself to continue digging further into this :) See the following code, which is quite self-explanatory:

Java:
```java
package mypackage;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;

public class MyClass {

  public static void tokenize(String filename) throws Exception {
    Files.readAllLines(Paths.get(filename)).forEach(line -> line.split(" "));
  }
}
```
Python:
```python
from absl import app
import jpype.imports
from jpype.types import *

jpype.startJVM(classpath=['target/jpype-test-0.1-jar-with-dependencies.jar'])

from mypackage import MyClass

def main(args):
    MyClass.tokenize("test.txt") # test.txt is a file with 400K identical lines: "This is a test"

if __name__ == '__main__':
    #app.run(main) # Using this, the JVM crashes if -Xint is not specified
    main(None) # This works all the time
```

**Comment by Thrameos** [comment]
Does it work without the import to absl?    I ran it without the absl import and it completed without issue.

This is sounding vaguely like another bug that we don't understand.  On some versions of numpy the blas library was compiled against a different version of pthreads library than the JVM.  This resulted in a very odd crash when numpy.linalg.inv was called.   The basic problem appears to be that depending on the order that calls are issued some of the threading code used by both blas and JVM are conflicting in memory layout resulting in a crash.   The fix for numpy was to call inv prior to starting the JVM, but I could see the bug working in the opposite direction as well in which some library is loaded before the JVM is started which is interfering with the operation of the JVM resulting in a threading lock (such as the one called by JIT) to fail in some dastardly fashion.

Assuming that is the case I would look to see what dynamic libraries are being loading by the absl call and see if any have a conflict with the copies loaded by the JVM.

**Comment by Thrameos** [comment]
I can confirm there is some type of crash.

```
Fatal Python error: Segmentation fault

Current thread 0x00007fffff7c0740 (most recent call first):
  File "testCrash.py", line 12 in main
  File "/home/nelson85/env/python3.6-unix/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
  File "/home/nelson85/env/python3.6-unix/lib/python3.6/site-packages/absl/app.py", line 303 in run
  File "testCrash.py", line 15 in <module>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fffff03ef47 (sent by kill), pid=7835, tid=7835
#
# JRE version: OpenJDK Runtime Environment (11.0.8+10) (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x3ef47]  gsignal+0xc7
#
# Core dump will be written. Default location: core.7835 (may not exist)
#
# An error report file with more information is saved as:
# /mnt/c/Users/nelson85/Documents/devel/open/jpype/hs_err_pid7835.log
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
#

Thread 1 "testCrash.py" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by Thrameos** [comment]
Second guess.  Another rare possibility is that absl could have install a signal handler.   Python and JVM don't play particularly nice on this front because JVM uses certain signal handlers as part of its normal operation.  In some cases the Python signal handlers intercept or prevent the JVM from receiving these normal operation exceptions resulting in anomalous behaviors.   I tried the usual pattern to disable the fault handlers but it had no effect.

**Comment by Thrameos** [comment]
Disabling the fault handler fixed the error for me.

```
def main(args):
    import faulthandler
    faulthandler.disable()
    MyClass.tokenize("test.txt") # test.txt is a file with 400K identical lines: "This is a test"
````

**Comment by karllessard** [comment]
Unfortunately, disabling the faulthandler didn't worked for me in my real app. I'm not able though to reproduce anymore the error in the sample app I gave you so it seems to me that the issue cannot be reproduced deterministically. Maybe that is your case as well?

**Comment by karllessard** [comment]
Note that your error seemed a bit different than mine, you had a SegFault while in my case, it is always a BusError with this message: `guarantee(cb != NULL && cb->is_nmethod()) failed: safepoint polling: pc must refer to an nmethod`

**Comment by Thrameos** [comment]
Yeah yours reads more like the pthread bug than the faulthandler bug.    Safepoint is a checked in a Pthread section of the code.   I found the source and it seems likely that there is something wrong in the threading support.  Unfortunately, that does not rule out the faulthandler as both can participate.

I am not sure why the faulthandler causes issues beyond there is a technical problem with Python chaining.  But it is really outside of JPype domain.   It is possible that the disabling of the handler also failed to restore the Java entry points.  I would recommend altering the absl module to disable installing the fault handler in the first place and trying again.   That was how I isolated the issue on my end (just disabled pieces until it ran).   It is possible that your app has some other places that deal with the fault handlers.   There was one attempt to install the handlers in app.main but unfortunately that is not the only way that handlers can get installed especially if there is C code involved.

I have not been able to reproduce the bug on my machine with the faulthandlers disabled.  Perhaps I need to try on a OSX machine.  Unfortunately it will be a while as I have to work with a coworker as I only have windows and Linux available.

**Comment by karllessard** [comment]
OK, mea culpa, I've just noticed you were disabling `faulthandler` in the `main` method, I was doing it before calling `app.run(main)`, which was useless since `absl` was [enabling it](https://github.com/abseil/abseil-py/blob/ddbd7d46d01fa71b0584e948d68fcd1d47bea0c4/absl/app.py#L368) right after.

So I confirm that disabling faulthandler in the main method resolves the issue on my side as well 👍

**Comment by Thrameos** [comment]
Okay.  Thank you for the contribution.  Now that I have a method to replicate the bug in the fault handler interaction I can potentially fix it, though I suspect that given the Python fault handler module is written entirely in C there is not much that I can do from my end.   I don't think I can even monkey patch to place a warning so that next poor guy doesn't run face first into it.

**Comment by karllessard** [comment]
If `absl` can fail to load `faulthandler` somehow, it would work as it uses a fail-safe approach in case it is missing. A super ugly fix could be something like `sys.modules['faulthandler']=None` before `absl` is imported. But that will only work in that very specific case, I'm sure you'll find out better ideas ;)

Thanks a lot for your support and for finding a viable solution to this!
