### ISSUE TITLE
JPype onJVMStart not documented

### ISSUE THREAD

**Issue by pelson** [jpype-project/jpype#938]
I learnt about ``jpype.onJVMStart`` through one of our issue threads, and realised I'd never seen it mentioned before. It doesn't seem to be a documented API. Can we add it to the built docs?

**Comment by Thrameos** [comment]
Sure it would be good to have it document.  It should be as easy as adding ``autodecorator: jpype.onJVMStart`` in ``doc/api.rst``  It has been there forever for internal use.  It was heavily used as we had a lot of code in each submodule that could not happen until the JVM was loaded, but it sort of shrank as more code was pushed into core.   The big issue was that the order of the execution was by registration, so minor changes in the import order caused differences in the jpype bootstrapping process which after I fixed it the nth time I decided that is was best centralized.

I think it is actually buggy because it returns None rather than the function.    I will fix that as well.
