### ISSUE TITLE
No matching overloads found for *static* method

### ISSUE THREAD

**Issue by lgharibashvili** [jpype-project/jpype#946]
I am getting TypeError when trying to call a static method without arguments:
` MyClass.MyMethod()
`
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: No matching overloads found for *static* com...MyClass.MyMethod(), options are:
        public final java.lang.String com...MyClass.MyMethod(int)
        public final java.lang.String com...MyClass.MyMethod()

When inspecting with type() function, type of MyClass is JClass and type of MyMethod is JMethod.
I am getting similar error when trying to pass an integer as an argument.
Please advise what may be the issue.

**Comment by Thrameos** [comment]
Neither MyMethod implementations are static at least according to the error message you provided.

Here is an example where I attempt to call a static method with the wrong arguments.  Notice that both the method requested and methods available found contain ``static`` and the method arguments don't match.
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    Test.method()
TypeError: No matching overloads found for *static* Test.method(), options are:
        public static void Test.method(int)
```

If a user attempts to call an instance method as a static then a user gets a message similar to the following.  Notice that only requested method contains ``static`` and the method list matches.   In order to call ``method`` in this case, the user would need to create an instance first.
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    Test.method(1)
TypeError: No matching overloads found for *static* Test.method(int), options are:
        public void Test.method(int)
```

Not sure how I can make the behavior more clear as this is a frequent source of programming errors especially with new users.  I tried to add extra emphasis with ``*static*`` as earlier versions of jpype required the user to go back an look as the method declaration to see the problem.  Though admittedly occasionally I fall in the trap myself when I fail to get a match, try a bunch of casting which fails, then perform the face palm when I read the error message more closely.   Unfortunately flashing red text is not OS independent. 😉

**Comment by lgharibashvili** [comment]
You are absolutely right, now I realize they were instance methods.
Now that I understand the problem, the exception also seems pretty clear.

Thank you for your help. I am closing the issue.
