### ISSUE TITLE
ERROR: JVM cannot be restarted.

### ISSUE THREAD

**Issue by emptyknowledge** [jpype-project/jpype#959]
stop jvm, then start jvm, get this error.

my code:
```
def test():
  jpype.startJVM()
  ...... other code
  jpype.shutdownJVM()

if __name__ == "__main__":
  test()
  test()
```

**Comment by John-Hennig** [comment]
This is expected behavior, in that it's a documented limitation. See [API doc of `jpype.shutdownJVM()`](https://jpype.readthedocs.io/en/latest/api.html#jpype.shutdownJVM):
>This method shuts down the JVM and disables access to existing Java objects. Due to limitations in the [sic] JPype, it is not possible to restart the JVM after being terminated.

**Comment by pelson** [comment]
A few other issues worth linking to: https://github.com/jpype-project/jpype/issues/393#issuecomment-493991448, and https://github.com/jpype-project/jpype/issues/84#issuecomment-157680233.

This isn't a limitation introduced by JPype, but rather by the underlying JNI.

(I can't close the issue, but recommend it should be closed as a "can't fix")

**Comment by emptyknowledge** [comment]
can't fix

**Comment by leopoletti** [comment]
Hello,

I know it cannot be fixed through jpype but is there any workaround based on what happen when the kernel is restarted? variable/memory cleaning link to JVM that we can perform may be without restarting the kernel?

**Comment by Thrameos** [comment]
I am not sure what you are referring to by kernel.   The JVM is a process level library and thus it lives as long as the process unless terminated prematurely with "shutdownJVM".   It has nothing to do with the kernel.

The official JVM stopped supporting restarting capabilities in Java 1.2  and there are as far as I know no implementations with the capability.   The JNI supports restarting or multiple JVMs, but without support from the JVM that is just useless capabilities.   

Unfortunately they uses statics in the JVM so that no more than one copy can be installed, and once started it installs OS hooks that it does not remove.   Thus you can't even unload the  JVM shared library and reload it to create a fresh copy.   

I personally feel that having a user callable "shutdown" is a mistake in JPype design.  The JVM was never intended to be run as a submodule.   Once started it needs to run until of the process.  Only when the process is preparing to exit should the JVM ever be told to begin shutdown procedures.
