### ISSUE TITLE
ImportError: cannot import name X from Y

### ISSUE THREAD

**Issue by cowwoc** [jpype-project/jpype#972]
JPype1 version 1.2.1
OpenJDK 16.0.1, Windows 10, Python 3.9

I am trying to run the following python code:

```
import os
import jpype.imports

print("cwd: %s" % os.getcwd())
jpype.startJVM("-ea", "--enable-preview", classpath=["target/classes"])

from java.lang import System
from test import Test

print(System.getProperty("java.class.path"))
Test()
exit(1)
```

I get this output:

```
cwd: C:\Users\Gili\Documents\myproject
Traceback (most recent call last):
  File "C:\Users\Gili\Documents\myproject\src\main\python\mypackage\__init__.py", line 8, in <module>
    from test import Test
ImportError: cannot import name 'Test' from 'test' (C:\Python39\lib\test\__init__.py)
```

where `C:\Users\Gili\Documents\myproject\target\classes` contains `test\Test.class`.

I've spent hours trying to debug this and I can't figure it out. If I invoke `java -cp target/classes test.Test` from command-line it works just fine.

**Comment by cowwoc** [comment]
Okay. So if I replace `from test import Test` with `Test = jpype.JClass("test.Test")`  then the code runs.

Any idea why the `import` is failing?

**Comment by Thrameos** [comment]
Generally speaking imports should be in a tld.   The defined tld for Java are "mil", "com", "org", "net", "gov",  and "edu".  Importing in others are only supported if there is not a conflict with Python.  There are a few common ways to get conflicts such as you are describing.   Installing a Python package with the same name, having a script with the same name, or having a directory with the same name.   

So you have one of ...
1) A site package named test.
2) A script called test.py in your PYTHON_PATH
3) A directory called test in your PYTHON_PATH

In the case of conflicts you can force using a particular Java (bypassing the Python search) by using ``jpype.JClass('test.Test')``.

**Comment by cowwoc** [comment]
I took the code directly from the "Getting Started" guide and it does not work. Take a look at this testcase:

[testcase.zip](https://github.com/jpype-project/jpype/files/6474292/testcase.zip)

If I run `from org.pkg import MyClass` I get:

```
Traceback (most recent call last):
  File "C:\Users\Gili\IdeaProjects\jpype\src\__init__.py", line 15, in <module>
    from org.pkg import MyClass
ImportError: cannot import name 'MyClass' from 'org.pkg' (unknown location)
```

If I replace this line with `jpype.JClass("org.pkg.MyClass")` it works fine. Can you reproduce this on your side?

**Comment by John-Hennig** [comment]
I, for one, cannot reproduce this. If I run `python -m src` from the `testcase` folder, I get this output:
```none
cwd: d:\temp\testcase
jvmpath: C:\programs\Java\bin\server\jvm.dll
jvmStarted: True
(16, 0, 1)
target/classes
Hello world
```

This is with JPype 1.2.1, Java 16.0.1, Python 3.9.4 on Windows 10.

**Comment by cowwoc** [comment]
@John-Hennig You are right. If I run from command-line I get the same output, but when I run the same command-line from inside IntelliJ it fails. I am scratching my head trying to figure out what is different.

Are you able to test with IntelliJ on your end?

**Comment by cowwoc** [comment]
Here is the output I get from command-line:

```
C:\Users\Gili\IdeaProjects\jpype>python\Scripts\python.exe C:/Users/Gili/IdeaProjects/jpype/src/__init__.py
cwd: C:\Users\Gili\IdeaProjects\jpype
jvmpath: C:\Program Files\Java\jdk-16.0.1\bin\server\jvm.dll
jvmStarted: True
(16, 0, 1)
target/classes
Hello world
```

and from IntelliJ:

```
C:\Users\Gili\IdeaProjects\jpype\python\Scripts\python.exe C:/Users/Gili/IdeaProjects/jpype/src/__init__.py
cwd: C:\Users\Gili\IdeaProjects\jpype
jvmpath: C:\Program Files\Java\jdk-16.0.1\bin\server\jvm.dll
jvmStarted: True
(16, 0, 1)
Traceback (most recent call last):
  File "C:\Users\Gili\IdeaProjects\jpype\src\__init__.py", line 15, in <module>
    from org.pkg import MyClass
ImportError: cannot import name 'MyClass' from 'org.pkg' (unknown location)

Process finished with exit code 1
```

**Comment by cowwoc** [comment]
I figured it out. I don't have PYTHONPATH set from command-line but IntelliJ sets it to:

`C:\Users\Gili\IdeaProjects\jpype;C:\Users\Gili\IdeaProjects\jpype\src\test\java;C:\Users\Gili\IdeaProjects\jpype\src\main\resources;C:\Users\Gili\IdeaProjects\jpype\src\main\java;C:/Users/Gili/IdeaProjects/jpype/target/classes;C:\Users\Gili\AppData\Roaming\JetBrains\IntelliJIdea2021.1\plugins\python\helpers\pycharm_matplotlib_backend;C:\Users\Gili\AppData\Roaming\JetBrains\IntelliJIdea2021.1\plugins\python\helpers\pycharm_display`

I'll play around with IntelliJ and hopefully I'll be able to figure this out. Closing this issue.

**Comment by cowwoc** [comment]
I'm going to go out on a limb and say I think I know what is going on.

IntelliJ seems to insist on setting `PYTHONPATH` to:

```
C:\Users\Gili\IdeaProjects\jpype;C:\Users\Gili\IdeaProjects\jpype\src\test\java;C:\Users\Gili\IdeaProjects\jpype\src\main\resources;C:\Users\Gili\IdeaProjects\jpype\src;C:/Users/Gili/IdeaProjects/jpype/target/classes;C:\Users\Gili\AppData\Roaming\JetBrains\IntelliJIdea2021.1\plugins\python\helpers\pycharm_matplotlib_backend;C:\Users\Gili\AppData\Roaming\JetBrains\IntelliJIdea2021.1\plugins\python\helpers\pycharm_display
```

For the most part this is harmless but it turns out that the presence of `C:/Users/Gili/IdeaProjects/jpype/target/classes` in the value triggers the aforementioned exception to be thrown.

https://jpype.readthedocs.io/en/latest/userguide.html#importing-java-classes says:

> Python always imports local directories as modules before calling the Java importer.

So am I right in thinking that in this case Python sees the target/classes directory and treats it as a Python module instead of calling the Java importer?

I wish I could figure out how to instruct IntelliJ to not add this directory to `PYTHONPATH`. It seems to set it no matter what I try. I even tried declaring my own `PYTHONPATH` environment variable, and it appended to it :(

**Comment by Thrameos** [comment]
Yeah, not much I can do with the priorities of imports.   Python doesn't call 3rd party importers until all of the default methods have failed.   So JPype can't import until after the others have been scanned and found to be missing.

The order as far as I am aware is 
1) Preloaded modules
2) Local script as module
3) Local directory as module
4) System directory as module  (PYTHONPATH)
5) 3rd party plugins.

My suggestions are use one of the following solutions.

1) Use ``JClass('test.Test')`` to get to the class.
2) Use ``JPackage('test').Test``  to access the hidden package.
3) Use ``jpype.imports.registerDomain('mytest', alias='test')`` to make rename your Java package to avoid a conflict.
4) Abuse the import system using sys modules to preload java package `test` so that your preferred package rules over local.  As the first priority is always preloaded this can work when there are conflicts.

As the last one is not obvious, here is some sample code...
```
import jpype
import jpype.imports
import sys
jpype.startJVM()
sys.modules['test']=jpype.JPackage('java')  # Preload `test` with a Java package
from test.lang import String  # This should fail because I have both a `test` and `test.py`, but preloaded modules are first priority always.
```

Please note that option 4 will cause problems with reimport as a change in those directories is likely to cause it to drop existing reload and scan again.

**Comment by cowwoc** [comment]
Thank you. Just to close off on this topic, when I was researching Java-Python bridges the number one complaint I read about jpype was that it's always difficult to get imports working correctly (and when something fails it's not obvious why).

To that end, I wish https://jpype.readthedocs.io/en/latest/quickguide.html would have clarified earlier on that if you run into *any* import problem stop banging your head and instead try using the `JClass` syntax right away. If that works then your problem is likely caused by `PYTHONPATH` containing the Java class directory.

**Comment by Thrameos** [comment]
Getting started is always the worst.   Java has really poor diagnostics to get class load and Python adds a bunch of pitfalls to the path.  Thus first time users thus have to navigate the problems of both which at times feels like working your way through a Dark Soul level.  That said once you navigate the problem cases it works well.  So it is just what happens when you inherit the baggage of two languages.   

Though I am not sure if I agree with that statement that if JClass works that means it is `PYTHONPATH` problem in general.  
Fundamentally importing is 
1) Deciding if a modules isn't found to call the JPype 3rd party import hooks.
2) Looking through with Jar reflection and Jar file system handles to find the package and class to load.
3) Calling ``JClass`` to wrap the Java class to make it into a Python class.

The problem you gave was a failure at step one.  Since it didn't decide to call JPype nothing that followed mattered.   But that is only one possible failure mode step 1.  The known places where JClass works and imports fail are:  class is not public, class has module permission problems (JNI can access, but Java cannot), security manager issues, PYTHONPATH conflict with file or directory, class is in jar file which lacks a directory listing, jar with invalid directory listing, multiple jars providing the same package, class is in jar file with MR directory on older JVM, conflict in customizer (rare), a dynamic class loader (rare), and maybe four others that I can't recall right now.   Once in a while there is an issue that I simply can't solve because it is so site specific I simply can't replicate  the conditions.   In almost all cases they were problems in which an assumption has been violated that only someone very familiar with Python or Java would ever think of. 

Unfortunately, as my company prohibits installation of certain IDEs (including IntelliJ), this issue was not one that I could assist with.

**Comment by cowwoc** [comment]
Speaking only for myself, I think JPype is great when Java-to-C bindings don't exist but I don't really want to bind to Python in the long run if I can avoid it.  I am far from an expert on this topic but two problems that come to mind are garbage collection and the global interpreter lock. I suspect the further you go down this road, the more leaky abstractions you'll run into which will force users to dig into the C, Python code when some problems occur (e.g. memory leaks).

Ideally, I want both the Java and Python bindings to invoke the same low-level C/C++ code under the hood and let Java and Python provide a higher-level API on top.

**Comment by Thrameos** [comment]
Well if your implementation is C under the hood, then certainly you may want to just implement direct Python and Java binds.  C++ is perhaps a bit worse as it adds another control path with exceptions that really pumps up the difficulty to both Java and CPython.  JPype is intended for the case in which the code is written in Java and access from Python is required.  Other tools are certainly better for other situations.    

However, JNI and CPython APIs are no walk in the park.  Memory leaks, resource management, and threading are not insignificant problem.   Even using JNI for well over 10 years, there are still mysteries when it comes the API interactions.  A single missed frame statement or forgetting to hold a reference the right way and it all crashes and burns.   CPython is even rougher as you add a whole other dimension of reference counting errors which JNI mercifully abstracted away.   The crash often won't land close enough to the initial injury to even know where to start debugging.  So unless you have control of the C interface to make it easy to add hooks that support the requirements of multiple languages (or your API is trivial), justifying writing more than one language binding from scratch may not be worth it.   You wouldn't believe the number of times I have pounded my head wondering why they just didn't give a callback with a closure option on an interface or some way to involve something that doesn't require dancing around implementing fake objects because the interface requires accessing one member of some huge structure.   To summarize,  language binds are always a lot of work and most projects can't afford the cost of maintaining more than one.

JPype has solved "most" of the problems of getting Python to call Java as well as a number of speed optimizations when sharing data.  But there are still edge cases such as cyclic references.   Java doesn't have a general method to handle foreign references (other RMI but that doesn't appear to work for local) and Python has no methods to cooperate with a second garbage collector.   Thus there will always be rough spots.

**Comment by cowwoc** [comment]
@Thrameos Sorry, the above comment was actually meant for https://github.com/pytorch/pytorch/issues/58973

I assume that in the case of PyTorch (and TensorFlow) the bulk of the code is implemented in C with a Python API layered on top. In that case, it sounds better to build a Java binding on top of the C API instead of building Java on top of Python on top of C...

**Comment by Thrameos** [comment]
No problem.  It really depends on what the C looks like.  If is a wrapper over mostly C code then adding another Java wrapper likely works.  If it is code like Numpy where Python is integral to the code then a reverse bridge may be a better option.

**Comment by kasparthommen** [comment]
@cowwoc I had the exact same problem. I solved by navigating to the run configuration of my Python script and entering "-E" (without quotes) in the "Interpreter options" field. This option disables the PYTHONPATH env variable that Intellij seems to insist on setting, see here:

https://docs.python.org/3/using/cmdline.html#cmdoption-e
