### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by cowwoc** [jpype-project/jpype#974]
Per https://stackoverflow.com/a/66529772/14731 the error message found at https://github.com/jpype-project/jpype/blob/24a2b95aefc2a59e7cf2c362a92ee5c6b13eb94f/jpype/imports.py#L201 is misleading. Consider clarifying that the class must be public but was X instead.

**Comment by Thrameos** [comment]
I am not sure if this is the only way that this particular error is generated.   

The issue here is that reflection methods is always supposed to find the class if the class is available.  If it isn't we then call forname which is supposed to return an error of some kind.   Typically missing dependencies, class no found, or instantiation error.  The issue if this call does not fail is an internal inconsistency.   

There are a number of reasons that the get error will not fail hence the non-committal error message.   Examples are classes that are not public but appear to be available with reflection (module permissions), classes which contain dynamic code which the code loader succeeds in finding on the second call, classes which reference classes with various problems.   We even had a class that loaded but only the second time it was accessed.  Basically if you can get a reference to the class but cant actually load as a public accessible for any reason, it then it will usually show up as one of these error types.   The difficulty being that if I make the error more specify it would very likely be even more misdirection as a missing public is merely one possible cause.   We could add a specify check if the forname returned a class which was not public and specifically call out that particular error, but covering all the different errors that lead to this point would be difficult.

**Comment by cowwoc** [comment]
The additional check is sufficient. Hopefully we can cover all cases as we encounter them.
