### ISSUE TITLE
AttributeError object name is truncated

### ISSUE THREAD

**Issue by cowwoc** [jpype-project/jpype#977]
Version 1.2.1

When I invoke `samplePoint.mode()` I get the following output:

`AttributeError: 'com.mycompany.SampleP' object has no attribute 'mode'`

But the class name is `com.mycompany.SamplePoint`. I can't figure out why the name is getting truncated at the end.

**Comment by Thrameos** [comment]
I think this is a function of Python name printing.   There is nothing in jpype that truncates names.

--Karl

**Comment by cowwoc** [comment]
Is jpype the one triggering the `AttributeError`?

**Comment by Thrameos** [comment]
No.  This is a Python class system is issuing that error.   I checked the JPype source code and there is no error message similar.   The place is occurs is ``pyjp_class.cpp`` and ``pyjp_object.cpp``   JPype provided the initial search and if it fails then it falls through to Python to do a larger search of the attributes.   When that fails the error is issued.     Thus the problem is simply that in Python they may have truncated the name to prevent buffer overruns (potential security issue).   The other potential source is in the Python typing system.  It may not be the print statement but rather the type name was chopped by ``type_new``.   You can tell by printing the class ``__name__`` variable.  It would take a bit of investigation to find the source.

```
PyObject *PyJPClass_getattro(PyObject *obj, PyObject *name)
{
        JP_PY_TRY("PyJPClass_getattro");
        if (!PyUnicode_Check(name))
        {
                PyErr_Format(PyExc_TypeError,
                                "attribute name must be string, not '%.200s'",
                                Py_TYPE(name)->tp_name);
                return NULL;
        }

        // Private members are accessed directly
        PyObject* pyattr = PyType_Type.tp_getattro(obj, name);
        if (pyattr == NULL)
                return NULL;   // <=== fall back to the Python getattro where the error gets issued.
        JPPyObject attr = JPPyObject::claim(pyattr);

        // Private members go regardless
        if (PyUnicode_GetLength(name) && PyUnicode_ReadChar(name, 0) == '_')
                return attr.keep();

        // Methods
        if (Py_TYPE(attr.get()) == PyJPMethod_Type)
                return attr.keep();

        // Don't allow properties to be rewritten
        if (!PyObject_IsInstance(attr.get(), (PyObject*) & PyProperty_Type))
                return attr.keep();

        const char *name_str = PyUnicode_AsUTF8(name);
        PyErr_Format(PyExc_AttributeError, "Field '%s' is static", name_str);
        return NULL;
        JP_PY_CATCH(NULL);
}
```

**Comment by cowwoc** [comment]
Yikes. I guess I'll drop this for now.
