### ISSUE TITLE
Allow Pass-by-reference semantics for arrays

### ISSUE THREAD

**Issue by kasparthommen** [jpype-project/jpype#991]
Check out this MWE:

1. Java code that modifies an array entry:
```java
package com.foo;

public class ArrayModifier {
    public static void changeArray(int[] array) {
        array[0] = 42;
    }
}
```

2. Python code that calls `changeArray()`:
```python
# jpype setup code
# ...

from com.foo import ArrayModifier

array = [1, 2, 3]
ArrayModifier.changeArray(array)
print(array)
```

This prints `[1, 2, 3]` instead of the expected `[42, 2, 3]`, suggesting that the array has been passed by value, not by reference. Why is that, and is this intended? Is there any way to avoid this and replicate pass-by-reference semantics for arrays passed between Python and Java?

**Comment by Thrameos** [comment]
A Python list is not a Java int[] so that best that we can do is convert a copy of the array.   Modifications to that copy cannot be preserved at least without very significant performance hits.   After all how to you determine which elements were changes such that the changes can be reflected back on the Python list?   If we pass in a list with 1000 values or a numpy array we would have to test each element to see if it was changed which would double the cost of the even if not a single element were changed.   (Technically it may be much worse than double as we would need to compare each element which mean convert, compare then replace the element in the list).

The solution to this is to simply use an Java int[] as the argument.   It can be modified and the values retrieved.
```

from com.foo import ArrayModifier
array = jpype.JInt[:]([1,2,3])
ArrayModifier.changeArray(array)
print(array)
```

**Comment by Thrameos** [comment]
There is an additional reason that copy back is not useful.   Consider the following code.

```
public class ArrayModifier {
     int[] values;
     public void init(int[] v)
     {
         this.values = v;
     }

     public void compute()
     {
        for (int i =0; i<values.length; ++i)
           values[i] *= 2;
     }
}
```

Now if we execute
```
import ArrayModifier
array = [1, 2, 3]
am = ArrayModifier()
am.init(array)  #  Copy back would not modify the array
am.compute() # The Java copy gets modified, but JPype has no idea that Python and Java should sync.
print(array) # Give original values.
```

Now try with our solution.
```
import ArrayModifier
array = jpype.JInt([1, 2, 3])
am = ArrayModifier()
am.init(array)  
am.compute() 
print(array) # The copy in Python and the copy in Java are the same, so we get the revised values back.
```

**Comment by kasparthommen** [comment]
Thanks a lot for the pointers, that works indeed the way I was hoping!

Maybe the documentation could be updated to highlight the difference between automatic array conversion (in which case pass-by-value semantics apply) and the `jpype.JXxx` types (with pass-by-reference)?

**Comment by Thrameos** [comment]
I looked over the documentation and agree that we can be more specific about what is a conversion where only the converted values are passed and use of native types in which modification is possible.  Technically Java is always pass by value as you can't write a swap function in Java.  It never allows pass by reference arguments.  However, you can change objects pointed to by an array or object which is always true because Java does not provide the concept of "const".   The closest concept is immutable collections and those do not support primitives.   Hence there is no way to know if method will attempt to modify a primitive array so that we can warn on conversion.

**Comment by kasparthommen** [comment]
Thanks. By "pass-by-reference" I actually meant passing the array reference (by value, with the goal of being able to modify its contents on the Java side and make that visible on the Python side) rather than passing the array *contents* by value. Your `JInt[:]` suggestion solves that problem perfectly, thus I'm closing this issue.

**Comment by alvin-yang68** [comment]
Hello, I'm new to JPype and has a related question. I'm wondering how are Java objects treated in terms of "pass-by-reference" vs "pass-by-value". For instance, suppose a Python script instantiates a Java object and then passes this object as an argument to a Java function or class method. Will the data encapsulated by this Java object first be serialized into Python (i.e. copied over) when it is instantiated and then deserialized back into Java once the function call happens (i.e. make another copy)? Thank you.

**Comment by Thrameos** [comment]
Java objects for the purposes of Python are wrappers that act as pointers.  When you pass the object to Java only the pointer is passed.   And then you get the object back the result is a new pointer which is not connected to the original.   Thus is you attach information to the wrapper it will be lost.   But in this case there is only one copy of the Java object.   If you pass the same pointer twice to Java and then checked to see if the identity of the object is the same you will get true.

The results are slightly different for Python objects passed to Java.  Because they have no presence in Java they must be converted.  As the converted object is discarded at the end of each call, each conversion is considered a separate instance in Java.   Thus if you pass a Python string twice and then checked to see if the identity were the same it would return false.
