### ISSUE TITLE
Advice for passing 1 million rows from Java to Python?

### ISSUE THREAD

**Issue by cowwoc** [jpype-project/jpype#993]
Hi,

I'm trying to convert a Java `List` containing ~1 million rows to a Python pandas `DataFrame`. According to the profiler >85% of the time is spent iterating over the Java collection. Is there a faster way to handle this kind of conversion?

**Comment by Thrameos** [comment]
Can you post an example of the code that is performing the conversion?   The iterator method takes several trips back and forth through the JNI layer so it likely is not that fast.   The other obvious issue is that if the collection is a LinkedList and the method being used to convert is calling "get(i)" to step through the list as opposed to using the actual iterator pattern, then the conversion time is O(n^2) rather than O(n) on the lookup.    So the critical factor is how was the conversion performed, and what is the type of the Java List.

**Comment by cowwoc** [comment]
Hey @Thrameos 

I was using `List<Map<String, Object>>` on the Java side. I took a look at the jpype documentation and noticed that numpy arrays can be memory-mapped directly on top of Java primitive arrays so I restructured the Java data in terms of primitive arrays and everything seems to fly now.

For example, here is how I convert a Java `long[]` to a python numpy array of dtype `long`:

```
self.timeEpochSeconds = np.array(java_dataset.timeEpochSeconds())
```

I did, however, have to convert `String` by hand like this:

```
        java_time = java_dataset.time()
        self.time = np.empty([java_time.length], dtype=str)
        for i in range(len(self.time)):
            self.time[i] = str(java_time[i])
```

Is there a faster way to convert strings (like I did for longs)?

On a side-note, I had to explicitly convert the types from Java to Python because pickle complains it cannot serialize python classes that reference Java types. Is there a better way to fix that problem?

**Comment by Thrameos** [comment]
I would have guessed the fastest would be

```
self.time = [ str(i) for i in java_time]
```

There is a section on Pickle in the docs.

**Comment by cowwoc** [comment]
I saw the section on Pickle in the docs but that only seems to cover the case where I am invoking Pickle directly, which I am not.

I am using pytorch which invokes Pickle under the hood which throws an exception when it encounters the Java classes. Is there a way to hook jpype's Pickle support into the built-in Pickle implementation in order for pytorch to use it?

**Comment by Thrameos** [comment]
Unfortunately I am not aware of any way to make pickle deal with Java classes natively.   A quick primer on the subject.  In Python 2 the pickle system was written in Python and thus was completely modifiable.  Starting in Python 3 they replaced it with a module which only has a small number of customization spots.   I was able to patch in to the dictionary function to add Java serializer to the process, but it requires a fresh copy each time the dump method is called, thus JPickler solution.   There is no way to hook in without adding to their table.  The context manager that pickle provides is stateless on the user interfaceable areas so it can't create a Java serializer and call it when needed.   There are hackish ways of monkey patching in that behavior, but they are too flawed for me to release part of JPype because it would cause all Pickle instances to share the Java serializer which has its own cache. (thus you would only be able to write the same object into one stream as if a second stream were encountered it would just put in a cache reference.)

There are solutions that require that Python add a few additional hooks (basically a start context and end context statement when dump is called.  That still breaks multithreading, so ultimately the solution would require that pickler pass a reference to itself to object being serialized so that it becomes more stateful.   It is not a heavy lift to make the modifications (just a day or two) but you have to convince the Python developers that it is a good feature and guide it through the process.

I studied the issue at length in Python 3.6 and perhaps the situation has improved, but as noone has posed the problem to Python devs it likely remains the same state as before.   There may be a clever solution.
 
Unfortunately due to a dispute with my employer, I am not able to contribute such hooks nor work with Python folks to make it happen.  (They won't let me sign the contributors licensing agreement).  Thus unless someone takes up the effort of adding hooks to make Pickle compatible with foreign objects and guides it through to a release JPickle is the only solution and it certainly won't work with 3rd party libraries.  Sorry.

Looking at the documentation it seems like you could pass a different pickle module to torch.

```
torch.save(obj, f, pickle_module=pickle, pickle_protocol=DEFAULT_PROTOCOL, _use_new_zipfile_serialization=True)
```

So you may be able to pass JPickle in or some layer that routes to JPickle.

**Comment by Thrameos** [comment]
I looked over the current Python code.  The state remains much the same as when I last looked.   Because the cPickler object never appears in the stack, it is invisible to system and thus not accessible within the ``__reduce__`` method by any normal means.  If I could get ahold of the picker when a Java object was created I could create a serializer object to use for encoding data.   There are kludges like defining a ``__reduce__`` method that uses the caller line to create a copy of the serializer in a map.  Unfortunately this has the serious defect that there is no way to delete the serializer when dump returns thus it would likely leak memory.  

In order for it to be possible to marshal a Java object either
1) The pickler needs to expose itself to the object that is being serialized so that we can install a state which will be destroyed with the pickler is complete.
2) The pickler needs to call user defined begin and end hook with something identifiable so that we can create needed state variables and kill them when the procedure is complete.

Without either of those the only way is to create a custom pickler (like JPickler) and pass it as the pickle object to the save method.

**Comment by cowwoc** [comment]
@Thrameos What about this? https://bugs.python.org/issue35900

**Comment by Thrameos** [comment]
That is an improvement to make is easier to build custom picklers.  It still does not export the pickler object to reduce.  Therefore still no way to get state.  You will just need to pass JPickler to torch.save and see if it works.

**Comment by cowwoc** [comment]
Closing this issue as Java arrays seem to be the best/only approach for now.
